### PR TITLE
osd: make PG::*Force* event structs public

### PR DESCRIPTION
**Pull request by wjwithagen**
Otherwise the compiler complains about it:
```
home/jenkins/workspace/ceph-master/src/osd/OSD.cc:8518:12: error: 'UnsetForceBackfill' is a protected member of 'PG'
              PG::UnsetForceBackfill())));
                  ^
/home/jenkins/workspace/ceph-master/src/osd/PG.h:1902:16: note: declared protected here
  TrivialEvent(UnsetForceBackfill)
               ^
/home/jenkins/workspace/ceph-master/src/osd/OSD.cc:8525:12: error: 'SetForceBackfill' is a protected member of 'PG'
              PG::SetForceBackfill())));
                  ^
/home/jenkins/workspace/ceph-master/src/osd/PG.h:1901:16: note: declared protected here
  TrivialEvent(SetForceBackfill)
               ^
/home/jenkins/workspace/ceph-master/src/osd/OSD.cc:8534:12: error: 'UnsetForceRecovery' is a protected member of 'PG'
              PG::UnsetForceRecovery())));
                  ^
/home/jenkins/workspace/ceph-master/src/osd/PG.h:1900:16: note: declared protected here
  TrivialEvent(UnsetForceRecovery)
               ^
/home/jenkins/workspace/ceph-master/src/osd/OSD.cc:8541:12: error: 'SetForceRecovery' is a protected member of 'PG'
              PG::SetForceRecovery())));
                  ^
/home/jenkins/workspace/ceph-master/src/osd/PG.h:1899:16: note: declared protected here
  TrivialEvent(SetForceRecovery)
               ^
4 errors generated.
```
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

### CODE REVIEW

**Comment by tchaikov** [comment]
@wjwithagen could you remove clang from the title, and explain why we need to make these struct public in the commit message?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-04-12_15:56:07-rados-wip-kefu-testing-2018-04-12-2211-distro-basic-mira/

failed tests are 

- tracked by http://tracker.ceph.com/issues/23699
- caused by #19117, #21188
- fixed by #21406
