### PR TITLE
common: include cleanup

### PR DESCRIPTION
**Pull request by MaxKellermann**
Another PR split from https://github.com/ceph/ceph/pull/60490

Due to remaining bugs in other subsystems, this PR contains the commits of https://github.com/ceph/ceph/pull/62844 plus a few more. I will drop them from this PR as soon as these other commits are merged.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by MaxKellermann** [comment]
jenkins test api

**Comment by MaxKellermann** [comment]
jenkins test make check

**Comment by MaxKellermann** [comment]
Anybody?

**Review by cbodley — APPROVED** [review]

**Review by Matan-B — COMMENTED** [review]
Crimson side is not ready for merging yet.

File: src/crimson/CMakeLists.txt [hunk 1]
```diff
@@ -96,6 +98,11 @@ add_library(crimson-common STATIC
   ${PROJECT_SOURCE_DIR}/src/crush/CrushTester.cc
   ${PROJECT_SOURCE_DIR}/src/global/global_context.cc
   ${PROJECT_SOURCE_DIR}/src/global/pidfile.cc
+  ${PROJECT_SOURCE_DIR}/src/include/filepath.cc
+  ${PROJECT_SOURCE_DIR}/src/include/object.cc
+  ${PROJECT_SOURCE_DIR}/src/include/types.cc
+  ${PROJECT_SOURCE_DIR}/src/include/utime.cc
+  ${PROJECT_SOURCE_DIR}/src/include/uuid.cc
```
[the remark this answers is not in the document]
Comment (MaxKellermann) [reply src/crimson/CMakeLists.txt:105]: Oh no. I knew the Crimson build was a fragile mess, and I always hoped it wouldn't collapse while I was moving code around. Apparently that has happened now with these simple changes.
I had a quick glance at the logs, but I only saw timeout errors. I have no idea how this PR could cause timeouts.

By the way, how many failures are "too many failures"? I was thinking more than zero is too many, but for example I know that Jenkins fails more often than not, and always I have to repeat Jenkins builds many times until they succeed.

File: src/tools/ceph-dencoder/CMakeLists.txt [hunk 2]
```diff
@@ -10,8 +10,6 @@ endif()
 
 set(dencoder_srcs
   ceph_dencoder.cc
-  ../../include/uuid.cc
```
Comment (vshankar) [inline src/tools/ceph-dencoder/CMakeLists.txt:13]: This seems to be causing a failure is fs suite: https://pulpito.ceph.com/yuriw-2025-05-20_19:06:31-fs-wip-yuri13-testing-2025-05-20-0805-distro-default-smithi/8291025/

```
2025-05-21T04:29:34.449 INFO:teuthology.orchestra.run.smithi031.stdout:^G^@^@^@./file1
2025-05-21T04:29:34.449 DEBUG:teuthology.orchestra.run.smithi031:> ceph-dencoder type string_wrapper import - decode dump_json
2025-05-21T04:29:34.510 INFO:teuthology.orchestra.run.smithi031.stderr:failed to dlopen("/usr/lib/ceph/denc/denc-mod-common.so"): /usr/lib/ceph/denc/denc-mod-common.so: undefined symbol: _ZN9sobject_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE
2025-05-21T04:29:34.532 INFO:teuthology.orchestra.run.smithi031.stderr:class 'string_wrapper' unknown
2025-05-21T04:29:34.534 DEBUG:teuthology.orchestra.run:got remote process result: 1
```

This failure has nothing to do with fs suite actually, just that a test in the fs suite uses `ceph-dencode` with decode type `string_wrapper`.

**Comment by ljflores** [comment]
ping @MaxKellermann - this PR failed QA.

**Comment by MaxKellermann** [comment]
> ping @MaxKellermann - this PR failed QA.

You mean the runtime linker error?
```
2025-05-21T04:29:34.510 INFO:teuthology.orchestra.run.smithi031.stderr:failed to dlopen("/usr/lib/ceph/denc/denc-mod-common.so"): /usr/lib/ceph/denc/denc-mod-common.so: undefined symbol: _ZN9sobject_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE
```

This is what I get after building Ceph-main with no patches:
```
$ ldd -r lib/denc-mod-common.so|grep generate_test_instances
undefined symbol: _ZN6uuid_d23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN16entity_addrvec_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN13entity_addr_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN25compressible_bloom_filter23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN11pow2_hist_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN10LogSummary23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN10EntityName23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN13entity_name_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN8LogEntry23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN10ghobject_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN7utime_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN13entity_inst_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN12DecayCounter23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN11SnapContext23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN13inline_data_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN9CryptoKey23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN12CrushWrapper23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN13file_layout_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN13SnapRealmInfo23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN12SloppyCRCMap23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN12bloom_filter23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
undefined symbol: _ZN9hobject_t23generate_test_instancesERNSt7__cxx114listIPS_SaIS2_EEE	(lib/denc-mod-common.so)
```

So there is already a lot wrong with Ceph builds, it just so happens that the libraries whose explicit dependencies are missing in the cmake files were already linked at runtime before this module gets loaded. This isn't design, just coincidence. My point is: Ceph is already broken, and this PR only makes this visible. Yet again! I'll check if I can add the already-missing dependencies to this PR.

**Comment by MaxKellermann** [comment]
Rebased & fixed linker failure.

**Comment by MaxKellermann** [comment]
Oh no. Compiler error in unrelated source:
```
/home/jenkins-build/build/workspace/ceph-api/src/rgw/rgw_multi_del.cc:54:26: error: use of undeclared identifier 'strict_strtoll'
   54 |     long long size_tmp = strict_strtoll(size->get_data(), 10, &err);
      |                          ^
```
Of course, this is an existing bug, and my PR only reveals it.... yet another one.

**Comment by idryomov** [comment]
> Compiler error in unrelated source

It looks like there is at least one more:
```
FAILED: src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o 
/usr/bin/ccache /usr/bin/clang++-19 -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_HAS_IO_URING -DBOOST_ASIO_NO_TS_EXECUTORS -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_RANDOM_DYN_LINK -DBOOST_RANDOM_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DHAVE_CONFIG_H -DLMDB_SAFE_NO_CPP_UTILITIES -DXXH_NO_INLINE_HINTS=1 -D_ARROW_EXIST -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__ -I/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/include -I/home/jenkins-build/build/workspace/ceph-pull-requests/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/services -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw -I/usr/include/lua5.3 -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/driver/rados -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/dmclock/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/dmclock/support/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/BLAKE3/c -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/store/rados -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/driver/dbstore -isystem /opt/ceph/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/api/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/exporters/jaeger/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/ext/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/sdk/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/xxHash -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/fmt/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/breakpad_project-prefix/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/breakpad_project-prefix/include/breakpad -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/arrow/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/s3select/rapidjson/include -g -Werror -fPIC -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -Wall -fno-strict-aliasing -fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith -Werror=format-security -Winit-self -Wno-unknown-pragmas -Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024 -DBOOST_ALLOW_DEPRECATED_HEADERS -Wpessimizing-move -Wredundant-move -Wno-inconsistent-missing-override -Wno-mismatched-tags -Wno-unused-private-field -Wno-address-of-packed-member -Wno-unused-function -Wno-unused-local-typedef -Wno-varargs -Wno-gnu-designator -Wno-missing-braces -Wno-parentheses -Wno-deprecated-register -Wno-vla-cxx-extension -DCEPH_DEBUG_MUTEX -D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -std=c++2b -MD -MT src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o -MF src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o.d -o src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o -c /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_lua_utils.cc
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_lua_utils.cc:247:27: error: no member named 'to_chars' in namespace 'std'
  247 |     auto [ptr, ec] = std::to_chars(std::begin(elapsed_str), std::end(elapsed_str), elapsed.count());
      |                      ~~~~~^
1 error generated.
```

**Comment by MaxKellermann** [comment]
> > Compiler error in unrelated source
> 
> It looks like there is at least one more:
> 
> ```
> FAILED: src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o 
> /usr/bin/ccache /usr/bin/clang++-19 -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_HAS_IO_URING -DBOOST_ASIO_NO_TS_EXECUTORS -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_RANDOM_DYN_LINK -DBOOST_RANDOM_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DHAVE_CONFIG_H -DLMDB_SAFE_NO_CPP_UTILITIES -DXXH_NO_INLINE_HINTS=1 -D_ARROW_EXIST -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__ -I/home/jenkins-build/build/workspace/ceph-pull-requests/build/src/include -I/home/jenkins-build/build/workspace/ceph-pull-requests/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/services -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw -I/usr/include/lua5.3 -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/driver/rados -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/dmclock/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/dmclock/support/src -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/BLAKE3/c -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/store/rados -I/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/driver/dbstore -isystem /opt/ceph/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/api/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/exporters/jaeger/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/ext/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/jaegertracing/opentelemetry-cpp/sdk/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/xxHash -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/fmt/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/breakpad_project-prefix/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/breakpad_project-prefix/include/breakpad -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/build/src/arrow/include -isystem /home/jenkins-build/build/workspace/ceph-pull-requests/src/s3select/rapidjson/include -g -Werror -fPIC -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -Wall -fno-strict-aliasing -fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith -Werror=format-security -Winit-self -Wno-unknown-pragmas -Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024 -DBOOST_ALLOW_DEPRECATED_HEADERS -Wpessimizing-move -Wredundant-move -Wno-inconsistent-missing-override -Wno-mismatched-tags -Wno-unused-private-field -Wno-address-of-packed-member -Wno-unused-function -Wno-unused-local-typedef -Wno-varargs -Wno-gnu-designator -Wno-missing-braces -Wno-parentheses -Wno-deprecated-register -Wno-vla-cxx-extension -DCEPH_DEBUG_MUTEX -D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -std=c++2b -MD -MT src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o -MF src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o.d -o src/rgw/CMakeFiles/rgw_common.dir/rgw_lua_utils.cc.o -c /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_lua_utils.cc
> /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_lua_utils.cc:247:27: error: no member named 'to_chars' in namespace 'std'
>   247 |     auto [ptr, ec] = std::to_chars(std::begin(elapsed_str), std::end(elapsed_str), elapsed.count());
>       |                      ~~~~~^
> 1 error generated.
> ```

This is a bug that was caused by commit d8adc49fa9dc9b13dd2da0fca3ea33582410bf5d (by @tchaikov), and it was merged two months *after* I submitted this PR. My PR was fine before the buggy commit got merged.

It is annoying that my PRs keep lingering until new Ceph bugs get merged which break my code....

**Comment by MaxKellermann** [comment]
> Oh no. Compiler error in unrelated source:
> 
> ```
> /home/jenkins-build/build/workspace/ceph-api/src/rgw/rgw_multi_del.cc:54:26: error: use of undeclared identifier 'strict_strtoll'
>    54 |     long long size_tmp = strict_strtoll(size->get_data(), 10, &err);
>       |                          ^
> ```
> 
> Of course, this is an existing bug, and my PR only reveals it.... yet another one.

And btw this bug was caused by 55f5b762c67fd7c177835e1a488692f012042d94 (by @AliMasarweh), three months after I submitted this PR.

File: src/tools/ceph-dencoder/CMakeLists.txt (hunk 2 above)
Comment (vshankar) [reply src/tools/ceph-dencoder/CMakeLists.txt:13]: I can confirm that the latest update by @MaxKellermann fixes this decoding issue.

**Comment by anrao19** [comment]
jenkins test make check

**Comment by anrao19** [comment]
jenkins test make check arm64

**Comment by anrao19** [comment]
jenkins test api

**Comment by anrao19** [comment]
jenkins test windows

**Comment by idryomov** [comment]
> Compiler error in unrelated source

... and this one pops up in the Windows build:
```
/home/ubuntu/ceph/src/test/librados/aio_cxx.cc:2394:46: error: use of undeclared identifier 'ceph_clock_now'
        cout << "sending pool EIO time: " << ceph_clock_now() << std::endl;
```

**Comment by MaxKellermann** [comment]
> > Compiler error in unrelated source
> 
> ... and this one pops up in the Windows build:
> 
> ```
> /home/ubuntu/ceph/src/test/librados/aio_cxx.cc:2394:46: error: use of undeclared identifier 'ceph_clock_now'
>         cout << "sending pool EIO time: " << ceph_clock_now() << std::endl;
> ```

This bug was introduced by commit 07319d9a37ef70b6422e26eba8a251f711db2c6b (by @NitzanMordhai) a month after I submitted this PR.

Sigh!

**Comment by MaxKellermann** [comment]
I added fixes for the new Ceph bugs you guys found. Let's see if that makes the CI happy, or if more bugs got added to Ceph meanwhile.

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests-arm64/78551/
> The following tests FAILED:
	 32 - run-rbd-unit-tests-61.sh (Failed)
	 34 - run-rbd-unit-tests-127.sh (Timeout)

**Comment by cbodley** [comment]
jenkins test make check arm64

**Comment by MaxKellermann** [comment]
Apparently that was just yet another spurious CI failure.

**Comment by vshankar** [comment]
This PR is under test in [https://tracker.ceph.com/issues/72445](https://tracker.ceph.com/issues/72445).

**Comment by idryomov** [comment]
Cleared the DNM label since @Matan-B has since approved the PR.

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/QA_main_2025#wip-vshankar-testing-20250806114233-debug
