### PR TITLE
pacific: test/cli-integration/rbd: iSCSI REST API responses aren't pretty-printed anymore

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/57389

---

backport of https://github.com/ceph/ceph/pull/47881
parent tracker: https://tracker.ceph.com/issues/57343

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
just ran into this test failure at https://pulpito.ceph.com/kchai-2022-09-03_01:50:21-rados-wip-pacific-update-fio-kefu-8-distro-default-smithi/7009273/ .

**Comment by idryomov** [comment]
https://pulpito.ceph.com/dis-2022-09-02_12:19:50-rbd-wip-dis-testing-pacific-distro-default-smithi/
https://pulpito.ceph.com/dis-2022-09-03_09:07:52-rbd-wip-dis-testing-pacific-distro-default-smithi/

**Comment by tchaikov** [comment]
```
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

the "make check" failure is a known issue, and should be fixed by #47803.

**Review by lxbsz — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test api
