### PR TITLE
PGLog: split divergent priors as well

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/11069

### CODE REVIEW

**Comment by tchaikov** [comment]
```
In file included from ./osd/PG.h:39:0,
                 from ./osd/OSD.h:20,
                 from osd/ClassHandler.cc:4:
./osd/PGLog.h: In member function 'void PGLog::split_into(pg_t, unsigned int, PGLog*)':
./osd/PGLog.h:405:22: error: 'struct hobject_t' has no member named 'get_hash'
       if ((i->second.get_hash() & mask) == child_pgid.m_seed) {
                      ^
```
might want to backport `hobject_t::get_hash()` introduced by 6de83d49 to firefly also.

**Comment by smithfarm** [comment]
@tchaikov: thanks!

**Comment by dachary** [comment]
@smithfarm I assume you did not cherry-pick -x 6de83d4 because it has conflicts. And that's why you chose to just add the get_hash function. In that case I think it's better to add that as a "Conflict" resolution in the original patch, with a comment explaining what you had to do and why you did it. So the reviewer understands the problem and can approve the solution you chose. 

The problem with a minimalist approach is that it may create problems with future backports, if they need the full extent of 6de83d4 instead of just the get_hash backport you did. If that happens it may be necessary to try to backport 6de83d4 in full and resolve the conflict. And it will be necessary to relate to the partial backport you did to explain why part of the patch was already there and not the rest. 

There seems to be only two rather limited conflicts when applying 6de83d4 (did not check if it compiles though, maybe that's the real problem). Did you try it ?

**Comment by smithfarm** [comment]
@dachary: Actually I did consider attempting to backport 6de83d4 but was too lazy. Now at your suggestion I made the attempt, but this 6de83d4 depends on 4c2828e.

**Comment by smithfarm** [comment]
@dachary: Now trying a new approach in a89983b

**Comment by dachary** [comment]
@smithfarm sensible approach, simpler !

**Comment by dachary** [comment]
@smithfarm do you mind cherry-pick -x and add a "Conflict" comment to explain your approach ?

**Comment by smithfarm** [comment]
@dachary: something like this?

**Comment by dachary** [comment]
@smithfarm perfect
