### PR TITLE
luminous: rgw: fixed "unrecognized arg" error when using "radosgw-admin zone rm".

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/41630

---

backport of https://github.com/ceph/ceph/pull/30060
parent tracker: https://tracker.ceph.com/issues/41184

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
Build failure:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_admin.cc: In function 'int get_cmd(const char*, const char*, const char*, bool*)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_admin.cc:807:38: error: 'match_str' was not declared in this scope
     if (match_str(cmd, "rm", "delete"))
                                      ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_admin.cc: In function 'int bucket_source_sync_status(RGWRados*, const RGWZone&, const RGWZone&, RGWRESTConn*, const RGWBucketInfo&, int, std::ostream&)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_admin.cc:2362:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t shard_id = 0; shard_id < total_shards; shard_id++) {
                                      ^
src/rgw/CMakeFiles/radosgw-admin.dir/build.make:62: recipe for target 'src/rgw/CMakeFiles/radosgw-admin.dir/rgw_admin.cc.o' failed
make[3]: *** [src/rgw/CMakeFiles/radosgw-admin.dir/rgw_admin.cc.o] Error 1
```

**Comment by smithfarm** [comment]
The bug this is fixing was presumably introduced by https://github.com/ceph/ceph/pull/19439 which went in post-luminous.

**Comment by smithfarm** [comment]
@cbodley I closed this upon analyzing it. The `del` and `delete` commands were unified to `rm` for the mimic release. See the mimic release notes [1]:

"Commands variously marked as del, delete, remove
etc. should now all be normalized as rm. Commands already
supporting alternatives to rm remain backward-compatible. This
changeset applies to the radosgw-admin tool as well."

My conclusion is that it doesn't make sense to backport this all the way back to luminous.

[1] https://ceph.com/releases/v13-2-0-mimic-released/
