### PR TITLE
build/ops: use .sx for PPC assembler file that needs preprocessor

### PR DESCRIPTION
**Pull request by smithfarm**
This fixes the ppc64le build which was broken by e1c3985148869c55b3725e208ec3bc5acf5fceae

Fixes: http://tracker.ceph.com/issues/20106
Signed-off-by: Tim Serong <tserong@suse.com>
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-20106/

**Comment by smithfarm** [comment]
With this, the POWER8 build fails in a different way:

```
[ 3849s] [ 71%] Linking CXX executable ../bin/ceph-syn
[ 3854s] [ 71%] Building CXX object src/osd/CMakeFiles/osd.dir/__/common/TrackedOp.cc.o
[ 3861s] ../lib/libcommon.a(crc32c_ppc.c.o): In function `crc32_vpmsum':
[ 3861s] /home/abuild/rpmbuild/BUILD/ceph-12.0.3+git.1496141193.c89563dbe2/src/common/crc32c_ppc.c:65: undefined reference to `__crc32_vpmsum'
[ 3861s] collect2: error: ld returned 1 exit status
[ 3861s] src/CMakeFiles/ceph-syn.dir/build.make:169: recipe for target 'bin/ceph-syn' failed
[ 3861s] make[2]: *** [bin/ceph-syn] Error 1
[ 3861s] CMakeFiles/Makefile2:1300: recipe for target 'src/CMakeFiles/ceph-syn.dir/all' failed
[ 3861s] make[1]: *** [src/CMakeFiles/ceph-syn.dir/all] Error 2
[ 3861s] make[1]: *** Waiting for unfinished jobs....
```

Now trying a straight revert.

**Comment by tchaikov** [comment]
@smithfarm since #15373 has been merged, can we close this one, and mark http://tracker.ceph.com/issues/20106 resolved?

**Comment by smithfarm** [comment]
@tchaikov Let's keep this open until I can do a test build. #15373 is doing the exact same thing as this PR except using `.S` instead of `.sx`, but according to the gcc manual there is no difference between the two.

**Comment by tchaikov** [comment]
agreed!

**Comment by smithfarm** [comment]
#15373 fixes the issue for us.
