### PR TITLE
mgr/cephadm: revamp ceph.conf distribution scheduling 

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Fixes

```
Traceback (most recent call last):
  File "mgr/cephadm/module.py", line 271, in __init__
    self.config_notify()
  File "mgr/cephadm/module.py", line 525, in config_notify
    self.config_notify_one(what)
  File "mgr/cephadm/module.py", line 531, in config_notify_one
    self.cache.distribute_new_etc_ceph_ceph_conf()
AttributeError: 'CephadmOrchestrator' object has no attribute 'cache'
```

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by sebastian-philipp** [comment]
Thanks kefu!

**Comment by ricardoasmarques** [comment]
This PR fixes an issue introduced in https://github.com/ceph/ceph/pull/35576

**Comment by sebastian-philipp** [comment]
```
test_orchestrator/module.py volumes/__init__.py
cephadm/module.py: note: In member "config_notify" of class "CephadmOrchestrator":
cephadm/module.py:522: error: Argument 2 to "setattr" has incompatible type "Dict[Any, Any]"; expected "str"
cephadm/module.py:524: error: Argument 2 to "getattr" has incompatible type "Dict[Any, Any]"; expected "str"
```

**Comment by sebastian-philipp** [comment]
~~green: http://pulpito.ceph.com/swagner-2020-07-28_08:28:33-rados:cephadm-wip-swagner3-testing-2020-07-27-1524-distro-basic-smithi/~~ (before the rebase)

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2020-07-30_07:40:52-rados:cephadm-wip-swagner-testing-2020-07-29-1507-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
ping @tchaikov
