### PR TITLE
os, crimson/osd: reoder ops in os::Transaction to mimic classical PGTransaction

### PR DESCRIPTION
**Pull request by rzarzynski**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
Locally it builds on gcc 11.2.1.

The `make check` bot is having the following problem:

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:979:13: error: no matching function for call to '__begin'
        = decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_base.h:586:5: note: in instantiation of template type alias '__range_iter_t' requested here
    using iterator_t = std::__detail::__range_iter_t<_Tp>;
```

which looks similar to https://groups.google.com/g/linux.debian.bugs.dist/c/38RLhzy1O7U. A Clang's bug?

File: src/crimson/osd/replicated_backend.cc [hunk 1]
```diff
@@ -38,31 +40,337 @@ ReplicatedBackend::_read(const hobject_t& hoid,
...
+ * High level transaction.
+ *
+ * Due to how clones, renames (and EC) are handled in RADOS, crimson
+ * needs something similar to PGTransaction. Unlike it, HLTransaction
+ * is just an extension (also from the memory arrangement's POV) to
+ * the low-level os::Transaction. These jettisonable memory areas
+ * helps to reorder operations.
+ */
+namespace crimson::osd {
+class HLTransaction {
```
Comment (athanatos) [inline src/crimson/osd/replicated_backend.cc:54]: The osd_op from the client is higher level still.  How about PGBackendTransaction (or PGBackend::Transaction) -- that way readers will quickly associate this structure with the interface that consumes it.

File: src/crimson/osd/replicated_backend.cc [hunk 2]
```diff
@@ -38,31 +40,337 @@ ReplicatedBackend::_read(const hobject_t& hoid,
...
+
+  void reorder_back(Op& op) {
+    const auto idx = std::distance(begin(), &op);
+    std::swap(*std::next(std::begin(*this), idx),
+              *std::next(std::begin(*this), ordered_tail_idx));
+    std::swap(op_data_locators[idx], op_data_locators[ordered_tail_idx]);
+    ++ordered_tail_idx;
+  }
+
+  ceph::os::Transaction& get_lltransaction() && {
```
Comment (athanatos) [inline src/crimson/osd/replicated_backend.cc:88]: get_futurized_store_transaction() -- again, let's just name things based on the interface that consumes them.

File: src/crimson/osd/replicated_backend.cc [hunk 3]
```diff
@@ -38,31 +40,337 @@ ReplicatedBackend::_read(const hobject_t& hoid,
...
+ * helps to reorder operations.
+ */
+namespace crimson::osd {
+class HLTransaction {
+public:
+  using Op = ceph::os::Transaction::Op;
+
+  HLTransaction(ceph::os::Transaction&& txn)
+    : txn(txn) {
+    if (!this->txn.empty()) {
```
Comment (athanatos) [inline src/crimson/osd/replicated_backend.cc:60]: Rename param to avoid shadowing the member variable.

File: src/crimson/osd/replicated_backend.cc [hunk 4]
```diff
@@ -38,31 +40,337 @@ ReplicatedBackend::_read(const hobject_t& hoid,
...
+          return true;
+        }
+      }
+      return false;
+    });
+#else
+    std::ranges::for_each(std::move(rng), [&hltxn](auto& op) {
+      hltxn.reorder_back(op);
+    });
+#endif
```
Comment (athanatos) [inline src/crimson/osd/replicated_backend.cc:359]: ?

**Review by athanatos — CHANGES_REQUESTED** [review]
It sounds like your long-term goal is to consume an HLTransaction directly throughout the process as we do with PGTransaction.  Why not just use PGTransaction itself?  A quick scan suggests that not much should be required to use it directly.

File: src/crimson/osd/replicated_backend.cc (hunk 4 above)
Comment (rzarzynski) [reply src/crimson/osd/replicated_backend.cc:359]: `PGTransaction` causes reordering to happen not only between the nodes but also within them (create-or-clone, then writes and so on). While testing in crimson-rados I haven't encountered the need for this yet.

**Comment by rzarzynski** [comment]
The internal layout of `PGTransaction` is very different than `os::Transaction`. Building one via scanning the low-level `txn` and then translating into different instance of `os::Trasaction` seemed quite painful, and thus nearly obliged to transition completely sooner than later. `HLTransaction` is just `os::Transaction` + extra memory, and thus the high -> low conversion could be quite efficient.

**Comment by athanatos** [comment]
The code structure here doesn't really seem like the cleanest way to do this.

The behavior you've added to ReplicatedBackend is a transformation of the passed in ceph::os::Transaction to a ceph::os::Transaction with a different ordering.  That transformation relies only on the internal structure of the ceph::os::Transaction and nothing else.  Moreover, the implementation uses internal details of ceph::os::Transaction's encoding.  This all seems like it belongs with ceph::os::Transaction with a single interface defined there along with unit tests since it doesn't seem to have any other dependencies.

PGTransaction has a fairly precise specification of it's behavior and requirements -- I'd also want to see a similarly precise explanation here, presumably at the interface boundary I mention above.
