### PR TITLE
cmake: more object libraries depend on legacy-option-headers

### PR DESCRIPTION
**Pull request by cbodley**
tracking down missing cmake dependencies that lead to compilation failures like:
```
src/common/options/legacy_config_opts.h:10:10: fatal error: 'immutable-object-cache_legacy_options.h' file not found
#include "immutable-object-cache_legacy_options.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
followup to https://github.com/ceph/ceph/pull/57011, https://github.com/ceph/ceph/pull/57693, https://github.com/ceph/ceph/pull/57583, etc

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
from https://jenkins.ceph.com/job/ceph-pull-requests/138196/
> Agent went offline during the build

**Comment by cbodley** [comment]
jenkins test make check

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by idryomov** [comment]
Quoting @cbodley's https://github.com/ceph/ceph/pull/58407#issuecomment-2206937381 here for reference since these details aren't included in commit messages:

> for better or worse, our ceph-common target is broken into a bunch of separate OBJECT libraries. these get bundled into ceph-common, but the object libraries themselves don't specify their own dependencies. modern cmake has gotten much better at treating these object libraries like normal targets (they carry transitive include directories, compile/link options, and link dependencies), so we just need to add the missing dependencies like Kefu did in #57583 and #57693
> 
> i audited each target from `grep -rw OBJECT --include=CMakeLists.txt` and added this dependency where i saw relevent includes like common/config.h or ceph_context.h etc. i pushed the result to #58414
> 
> > [200/2743] Building CXX object src/erasure-code/lrc/CMakeFiles/ec_lrc.dir/ErasureCodePluginLrc.cc.o
> > FAILED: src/erasure-code/lrc/CMakeFiles/ec_lrc.dir/ErasureCodePluginLrc.cc.o
> 
> ec_lrc isn't itself an OBJECT library, but depends on some; this failure was addressed by adding that dependency to the crush_objs target. i was able to verify that by building the target, removing the generated headers from build/include/*options.h, and rebuilding the target

**Comment by idryomov** [comment]
Here is another failure that seems to be related:
```
[49/1757] Building CXX object src/auth/CMakeFiles/common-auth-objs.dir/AuthClientHandler.cc.o
FAILED: src/auth/CMakeFiles/common-auth-objs.dir/AuthClientHandler.cc.o 
/usr/bin/ccache /usr/bin/clang++-14 -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_HAS_IO_URING -DBOOST_ASIO_NO_TS_EXECUTORS -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__ -I/home/jenkins-build/build/workspace/ceph-api/build/src/include -I/home/jenkins-build/build/workspace/ceph-api/src -isystem /opt/ceph/include -isystem /home/jenkins-build/build/workspace/ceph-api/build/include -isystem /home/jenkins-build/build/workspace/ceph-api/src/jaegertracing/opentelemetry-cpp/api/include -isystem /home/jenkins-build/build/workspace/ceph-api/src/jaegertracing/opentelemetry-cpp/exporters/jaeger/include -isystem /home/jenkins-build/build/workspace/ceph-api/src/jaegertracing/opentelemetry-cpp/ext/include -isystem /home/jenkins-build/build/workspace/ceph-api/src/jaegertracing/opentelemetry-cpp/sdk/include -isystem /home/jenkins-build/build/workspace/ceph-api/src/xxHash -isystem /home/jenkins-build/build/workspace/ceph-api/src/fmt/include -g -Werror -fPIC -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -Wall -fno-strict-aliasing -fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith -Werror=format-security -Winit-self -Wno-unknown-pragmas -Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024 -Wpessimizing-move -Wredundant-move -Wno-inconsistent-missing-override -Wno-mismatched-tags -Wno-unused-private-field -Wno-address-of-packed-member -Wno-unused-function -Wno-unused-local-typedef -Wno-varargs -Wno-gnu-designator -Wno-missing-braces -Wno-parentheses -Wno-deprecated-register -DCEPH_DEBUG_MUTEX -D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -std=c++20 -MD -MT src/auth/CMakeFiles/common-auth-objs.dir/AuthClientHandler.cc.o -MF src/auth/CMakeFiles/common-auth-objs.dir/AuthClientHandler.cc.o.d -o src/auth/CMakeFiles/common-auth-objs.dir/AuthClientHandler.cc.o -c /home/jenkins-build/build/workspace/ceph-api/src/auth/AuthClientHandler.cc
In file included from /home/jenkins-build/build/workspace/ceph-api/src/auth/AuthClientHandler.cc:23:
In file included from /home/jenkins-build/build/workspace/ceph-api/src/auth/none/AuthNoneClientHandler.h:20:
In file included from /home/jenkins-build/build/workspace/ceph-api/src/common/ceph_context.h:41:
In file included from /home/jenkins-build/build/workspace/ceph-api/src/common/config_proxy.h:6:
In file included from /home/jenkins-build/build/workspace/ceph-api/src/common/config.h:27:
In file included from /home/jenkins-build/build/workspace/ceph-api/src/common/config_values.h:59:
/home/jenkins-build/build/workspace/ceph-api/src/common/options/legacy_config_opts.h:1:10: fatal error: 'global_legacy_options.h' file not found
#include "global_legacy_options.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
@cbodley Could you please confirm that it's taken care of by these changes?

**Comment by cbodley** [comment]
> @cbodley Could you please confirm that it's taken care of by these changes or alternatively that it's a regression from #58238?

common-auth-objs already depended on legacy-option-headers, so that looks like a regression

**Comment by cbodley** [comment]
clean builds in https://shaman.ceph.com/builds/ceph/wip-cmake-object-library-legacy-headers/
