### PR TITLE
mimic: mds: cleanup unneeded client_snap_caps when splitting snap inode

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/40444

---

backport of https://github.com/ceph/ceph/pull/28190
parent tracker: https://tracker.ceph.com/issues/39987

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick Done

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc: In member function 'CInode* MDCache::cow_inode(CInode*, snapid_t)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:1589:19: error: 'vec' is not a member of 'MDSContext'
       MDSContext::vec finished;
                   ^~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:1600:68: error: 'finished' was not declared in this scope
    lock->take_waiting(SimpleLock::WAIT_STABLE|SimpleLock::WAIT_RD, finished);
                                                                    ^~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:1600:68: note: suggested alternative: 'Finisher'
    lock->take_waiting(SimpleLock::WAIT_STABLE|SimpleLock::WAIT_RD, finished);
                                                                    ^~~~~~~~
                                                                    Finisher
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:1604:26: error: 'finished' was not declared in this scope
       mds->queue_waiters(finished);
                          ^~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mds/MDCache.cc:1604:26: note: suggested alternative: 'Finisher'
       mds->queue_waiters(finished);
                          ^~~~~~~~
                          Finisher
src/mds/CMakeFiles/mds.dir/build.make:179: recipe for target 'src/mds/CMakeFiles/mds.dir/MDCache.cc.o' failed
make[3]: *** [src/mds/CMakeFiles/mds.dir/MDCache.cc.o] Error 1
```

**Comment by smithfarm** [comment]
The `Docs: build check` failure is unrelated and addressed by https://github.com/ceph/ceph/pull/30663

**Comment by smithfarm** [comment]
@batrick @ukernel Please look at the Conflicts section of the new commit - it explains how I solved the build failure.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-10-07-1952-mimic](https://trello.com/c/tcdfLTno/710-wip-yuri3-testing-2019-10-07-1952-mimic)

**Comment by smithfarm** [comment]
jenkins test docs
