### PR TITLE
octopus: os/bluestore/AvlAllocator: introduce bluestore_avl_alloc_ff_max_* options

### PR DESCRIPTION
**Pull request by mfoliveira**
backport tracker: https://tracker.ceph.com/issues/48477
backport of #38148
parent tracker: https://tracker.ceph.com/issues/48272

backport tracker: https://tracker.ceph.com/issues/53104
backport of #41398
parent tracker: https://tracker.ceph.com/issues/53085

backport tracker: https://tracker.ceph.com/issues/53102
backport of #41825
parent tracker: https://tracker.ceph.com/issues/53086

backport tracker: https://tracker.ceph.com/issues/53100
backport of #41615
parent tracker: https://tracker.ceph.com/issues/53087

These backport PRs are for tracker https://tracker.ceph.com/issues/52804

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by mfoliveira** [comment]
Chart with results / improvements: https://tracker.ceph.com/issues/52804#note-20

`run-make-check.sh` looks good (3 unrelated failures)
- 2 python (apparently syntax error checks)
- 1 rgw dmclock sched (intemittent failure)

```
98% tests passed, 3 tests failed out of 187

Total Test time (real) = 408.90 sec

The following tests FAILED:
          1 - run-tox-mgr (Failed)
          3 - run-tox-python-common (Failed)
        179 - unittest_rgw_dmclock_scheduler (Failed)
        
```

An event of 179 passing:
```
$ ctest -j32 -R 'run-tox-mgr|run-tox-python-common|unittest_rgw_dmclock_scheduler'
Test project /home/ubuntu/ceph/build
    Start   2: run-tox-mgr-insights
    Start   1: run-tox-mgr
    Start   3: run-tox-python-common
    Start 179: unittest_rgw_dmclock_scheduler
1/4 Test #179: unittest_rgw_dmclock_scheduler ...   Passed    0.04 sec
2/4 Test   #2: run-tox-mgr-insights .............   Passed    0.94 sec
3/4 Test   #3: run-tox-python-common ............***Failed    3.57 sec
4/4 Test   #1: run-tox-mgr ......................***Failed    7.31 sec

50% tests passed, 2 tests failed out of 4

Total Test time (real) =   7.32 sec

The following tests FAILED:
          1 - run-tox-mgr (Failed)
          3 - run-tox-python-common (Failed)
Errors while running CTest
```



Error details:

```        
Errors while running CTest

...

148/187 Test #179: unittest_rgw_dmclock_scheduler ..........***Failed    0.09 sec
...
[ RUN      ] Queue.SpawnAsyncRequest
/home/ubuntu/ceph/src/test/rgw/test_rgw_dmclock_scheduler.cc:428: Failure
Value of: context.stopped()
  Actual: false
Expected: true
[  FAILED  ] Queue.SpawnAsyncRequest (0 ms)
...
 1 FAILED TEST

...

159/187 Test   #3: run-tox-python-common ...................***Failed   20.86 sec
...
=================================== FAILURES ===================================
________________________________ ceph/utils.py _________________________________
73: error: syntax error in type comment
_________________________________ test session _________________________________
mypy exited with status 2.
===================================== mypy =====================================
Found 1 error in 1 file (checked 24 source files)
=========================== short test summary info ============================
FAILED ceph/utils.py::mypy
FAILED ::mypy
======================== 2 failed, 200 passed in 0.95s =========================
...


168/187 Test   #1: run-tox-mgr .............................***Failed   49.55 sec
...
cephadm/module.py:2269: error: syntax error in type comment
Found 106 errors in 1 file (checked 10 source files)
ERROR: InvocationError for command /home/ubuntu/ceph/src/pybind/mgr/.tox/mypy/bin/mypy --config-file=../../mypy.ini cephadm/module.py mgr_module.py dashboard/module.py prometheus/module.py mgr_util.py orchestrator/__init__.py progress/module.py rook/module.py test_orchestrator/module.py volumes/__init__.py (exited with code 2)
...
```

**Comment by tchaikov** [comment]
the doc build failure should be addressed by #43748

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test docs

**Comment by ifed01** [comment]
jenkins test make check

**Review by ifed01 — APPROVED** [review]

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by ifed01** [comment]
@mfoliveira - could you please push this branch again (with some insignificant modification) to retrigger failed docs builds

**Comment by mfoliveira** [comment]
@ifed01 sure! it took a rebase too, but the docs build checks are now green. also done for #43745  (Pacific); thanks for the ping.

**Comment by yuriw** [comment]
jenkins test api
