### PR TITLE
mgr/cephadm: Purge deleted services

### PR DESCRIPTION
**Pull request by sebastian-philipp**
We'd like to keep the spec in the store, while we're cleaning
up all the daemons. Reason is to clean up the
config and config-key store when the last daemon of a
service is deleted.

Thus, If no daemon is deployed for a deleted service, purge it.

Fixes: https://tracker.ceph.com/issues/48597

## TODOs:

- [x] handle deleted services in `orch ls (--export)`
- [x] fix the exporter purge
- [x] verify purge in pytest
- [x] add purge for MDS service

## See also

- #38844 for a failed approach
- #38549 for more spec store changes

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

File: src/pybind/mgr/cephadm/services/cephadmservice.py [hunk 1]
```diff
@@ -568,6 +568,13 @@ def get_active_daemon(self, daemon_descrs: List[DaemonDescription]) -> DaemonDes
         # if no mds found, return empty Daemon Desc
         return DaemonDescription()
 
+    def purge(self, service_name: str) -> None:
+        self.mgr.check_mon_command({
+            'prefix': 'config rm',
+            'who': service_name,
+            'name': 'mds_join_fs',
+        })
```
Comment (sebastian-philipp) [inline src/pybind/mgr/cephadm/services/cephadmservice.py:576]: hm. Feels as if we should ignore errors here. thoughts?

File: src/pybind/mgr/cephadm/module.py [hunk 2]
```diff
@@ -1692,12 +1694,13 @@ def remove_daemons(self, names):
     def remove_service(self, service_name: str) -> str:
         self.log.info('Remove service %s' % service_name)
         self._trigger_preview_refresh(service_name=service_name)
+        if service_name in self.spec_store:
+            if self.spec_store[service_name].spec.service_type in ('mon', 'mgr'):
+                return f'Unable to remove {service_name} service.\n' \
+                       f'Note, you might want to mark the {service_name} service as "unmanaged"'
```
Comment (adk3798) [inline src/pybind/mgr/cephadm/module.py:1700]: Since this is only ever printed for mgr and mon, is it a good idea to tell users to mark those services as unmanaged? If they do and then proceed to remove them won't everything break down?

**Review by adk3798 — APPROVED** [review]
LGTM. I like the change to all/active_specs function rather than directly messing with the specs field of the SpecStore. Did some local testing with these changes and it seems to fix the issue laid out in the attached tracker: 
image
Also deployed and removed iscsi and ha-rgw when testing to be safe since those are underrepresented in teuthology. They were unaffected by the changes here.

File: src/pybind/mgr/cephadm/services/cephadmservice.py (hunk 1 above)
Comment (adk3798) [reply src/pybind/mgr/cephadm/services/cephadmservice.py:576]: What kind of errors are you expecting here other than if the provided service name is wrong?

Comment (sebastian-philipp) [reply src/pybind/mgr/cephadm/services/cephadmservice.py:576]: things like someone removed `mds_join_fs` manually. I have no concrete idea. But I#d really like to prevent an infinite loop of always trying to purge this service and failing every time. Sound like a great way to make people really scared.

File: src/pybind/mgr/cephadm/module.py (hunk 2 above)
Comment (sebastian-philipp) [reply src/pybind/mgr/cephadm/module.py:1700]: Right. have a better idea for a text? 

I mean if we decide that we **always** want to have specs for mon and mgr, then we simply should not allow users to delete those services. period. Cause otherwise we can no longer manage the cluster. But should we really recommend setting unmanaged?

**Comment by sebastian-philipp** [comment]
```
2021-02-04T14:18:49.675 DEBUG:teuthology.orchestra.run.smithi026:> sudo /home/ubuntu/cephtest/cephadm --image quay.ceph.io/ceph-ci/ceph:da5eb249db89348652c94d25666d9fbdb0ef1606 shell -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --fsid 93566668-66f3-11eb-8fc5-001a4aab830c -- ceph orch daemon add mon 'smithi026:
2021-02-04T14:18:51.354 INFO:teuthology.orchestra.run.smithi026.stderr:Error EINVAL: Unable to add a Daemon without Service.
2021-02-04T14:18:51.354 INFO:teuthology.orchestra.run.smithi026.stderr:Please use `ceph orch apply ...` to create a Service.
2021-02-04T14:18:51.354 INFO:teuthology.orchestra.run.smithi026.stderr:Note, you might want to create the service with "unmanaged=true"
```
https://pulpito.ceph.com/swagner-2021-02-03_11:39:27-rados:cephadm-wip-swagner3-testing-2021-02-03-1059-distro-basic-smithi/5853839

**Comment by sebastian-philipp** [comment]
* https://pulpito.ceph.com/swagner-2021-02-10_11:41:39-rados:cephadm-wip-swagner-testing-2021-02-09-1126-distro-basic-smithi/
* https://pulpito.ceph.com/swagner-2021-02-11_10:31:33-rados:cephadm-wip-swagner-testing-2021-02-09-1126-distro-basic-smithi/

Failures:

* https://tracker.ceph.com/issues/49259
* e2e test

**Comment by tchaikov** [comment]
@sebastian-philipp 

```
cephadm/module.py:51: note: In module imported here,
cephadm/__init__.py:1: note: ... from here:
cephadm/services/monitoring.py: note: In member "prepare_create" of class "AlertmanagerService":
cephadm/services/monitoring.py:104: error: "SpecStore" has no attribute "specs"; maybe "_specs"?
cephadm/services/monitoring.py:106: error: "SpecStore" has no attribute "specs"; maybe "_specs"?
cephadm/module.py:49: note: In module imported here,
cephadm/__init__.py:1: note: ... from here:
cephadm/services/nfs.py: note: In member "prepare_create" of class "NFSService":
cephadm/services/nfs.py:33: error: "SpecStore" has no attribute "specs"; maybe "_specs"?
cephadm/services/nfs.py:35: error: "SpecStore" has no attribute "specs"; maybe "_specs"?
cephadm/module.py:48: note: In module imported here,
cephadm/__init__.py:1: note: ... from here:
cephadm/services/ha_rgw.py: note: In member "prepare_create" of class "HA_RGWService":
cephadm/services/ha_rgw.py:26: error: "SpecStore" has no attribute "specs"; maybe "_specs"?
cephadm/services/ha_rgw.py:28: error: "SpecStore" has no attribute "specs"; maybe "_specs"?
cephadm/module.py:47: note: In module imported here,
```

i think the reason of the failure above is that this change was racing with 2c7f899124207d0d4866e16d9eb5609777ea22e8.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp
> 
> ```
> ...
> ... "SpecStore" has no attribute "specs"; maybe "_specs"?
> ...
> ```
> 
> i think the reason of the failure above is that this change was racing with [2c7f899](https://github.com/ceph/ceph/commit/2c7f899124207d0d4866e16d9eb5609777ea22e8).

#39458

**Comment by sebastian-philipp** [comment]
regression: #39649
