### PR TITLE
cmake: add WITH_SYSTEM_BLAKE3 and WITH_SYSTEM_XXHASH

### PR DESCRIPTION
**Pull request by cbodley**
~~based on ~~https://github.com/ceph/ceph/pull/55076~~ https://github.com/ceph/ceph/pull/58429 for now~~

centos 9 and fedora have up-to-date blake3-devel and xxhash-devel packages. adds cmake options WITH_SYSTEM_BLAKE3/XXHASH (off by default) to build against those packages instead of their submodules. ceph.spec.in adds those rpm dependencies and tells cmake to use them

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

File: src/rgw/rgw_xxh_digest.h [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+ */
+
+#pragma once
+
+#include <stdint.h>
+#include <stdio.h>
+
+#define XXH_INLINE_ALL 1 /* required for streaming variants */
+#include <xxhash.h>
+#include <xxh3.h>
```
Comment (cbodley) [inline src/rgw/rgw_xxh_digest.h:23]: without this <xxh3.h> include, i was seeing this error with WITH_SYSTEM_XXHASH:
```
In file included from src/rgw/rgw_cksum_digest.h:21,
                 from src/rgw/rgw_cksum_pipe.h:23,
                 from src/rgw/rgw_rest_s3.cc:74:
src/rgw/rgw_xxh_digest.h: At global scope:
src/rgw/rgw_xxh_digest.h:27:18: error: field ‘s’ has incomplete type ‘XXH3_state_t’ {aka ‘XXH3_state_s’}
   27 |     XXH3_state_t s;
      |                  ^
In file included from src/rgw/rgw_xxh_digest.h:20:
/usr/include/xxhash.h:1130:16: note: forward declaration of ‘XXH3_state_t’ {aka ‘struct XXH3_state_s’}
 1130 | typedef struct XXH3_state_s XXH3_state_t;
      |                ^~~~~~~~~~~~
src/rgw/rgw_xxh_digest.h: In constructor ‘rgw::digest::XXH3::XXH3()’:
src/rgw/rgw_xxh_digest.h:33:7: error: ‘XXH3_INITSTATE’ was not declared in this scope
   33 |       XXH3_INITSTATE(&s);
      |       ^~~~~~~~~~~~~~
```

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/138269/
```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "rgw_common" of type STATIC_LIBRARY
    depends on "dbstore" (weak)
    depends on "dbstore_lib" (weak)
    depends on "sqlite_db" (weak)
  "dbstore_lib" of type SHARED_LIBRARY
    depends on "rgw_common" (weak)
    depends on "dbstore" (weak)
    depends on "sqlite_db" (weak)
  "dbstore" of type STATIC_LIBRARY
    depends on "dbstore_lib" (weak)
    depends on "rgw_common" (weak)
    depends on "sqlite_db" (weak)
  "sqlite_db" of type STATIC_LIBRARY
    depends on "dbstore_lib" (weak)
    depends on "rgw_common" (weak)
    depends on "dbstore" (weak)
    depends on "dbstore_lib" (strong)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
```

**Comment by cbodley** [comment]
> CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):

bisected to commit "cmake: use xxHash's unofficial cmake support". no idea why 🤷 but i've added a commit that changes dbstore_lib to a static library as a workaround

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/77193/
```
src/mon/OSDMonitor.cc:73:
src/common/Checksummer.h:11:10: fatal error: 'xxhash.h' file not found
#include <xxhash.h>
         ^~~~~~~~~~
1 error generated.
```
