### PR TITLE
octopus: ceph.spec.in: remove build directory at end of %install

### PR DESCRIPTION
**Pull request by tserong**
backport tracker: https://tracker.ceph.com/issues/55099

---

backport of https://github.com/ceph/ceph/pull/45664
parent tracker: https://tracker.ceph.com/issues/55079

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by tserong** [comment]
That force push was just adding Conflicts info to the commit message

**Comment by tserong** [comment]
This also needs #45705

**Review by tchaikov — APPROVED** [review]

**Comment by tserong** [comment]
jenkins test docs please

**Comment by tserong** [comment]
jenkins test docs please

**Comment by tchaikov** [comment]
```
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/jinja2/__init__.py)

Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/bin/sphinx-build", line 5, in 
    from sphinx.cmd.build import main
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/sphinx/cmd/build.py", line 25, in 
    from sphinx.application import Sphinx
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/sphinx/application.py", line 43, in 
    from sphinx.registry import SphinxComponentRegistry
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/sphinx/registry.py", line 24, in 
    from sphinx.builders import Builder
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 26, in 
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/sphinx/util/rst.py", line 21, in 
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.8/site-packages/jinja2/__init__.py)
```

hi Tim, the doc build failure should be addressed by #45972. before it is merged, i think we need to live with the build failure =(

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
jenkins render docs

**Comment by tserong** [comment]
Rebased to pick up docs fix

**Comment by tserong** [comment]
Dammit, now it's failing API tests because "apache-libcloud 3.5.1 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible."
