### PR TITLE
common: Make spinlock delay more conventional

### PR DESCRIPTION
**Pull request by badone**
The accepted method of implementing a spinlock delay is the "pause"
instruction.

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

File: src/common/simple_spin.cc [hunk 1]
```diff
@@ -18,9 +18,12 @@
 #include <stdint.h>
 #include <pthread.h>
 
-static uint32_t bar = 13;
-static uint32_t *foo = &bar;
- 
+#if (__arm__ || __aarch64__)
```
Comment (tchaikov) [inline src/common/simple_spin.cc]: better off using 
```c
#if defined(__arm__) || defined(__aarch64)
```
and might be better just put this inline assembly in `simple_spin_lock()` instead of introducing another macro.

File: src/common/simple_spin.cc [hunk 2]
```diff
@@ -18,9 +18,12 @@
...
+#define cpu_relax() asm volatile("yield": : :"memory")
```
Comment (tchaikov) [inline src/common/simple_spin.cc]: why would you want to add a memory barrier here?

**Comment by branch-predictor** [comment]
In my limited testing, I don't see any impact from this change.

File: src/common/simple_spin.cc (hunk 1 above)
Comment (badone) [inline src/common/simple_spin.cc]: Modelled on our existing code in src/test/test_arch.cc should it be changed as well?

File: src/common/simple_spin.cc (hunk 2 above)
Comment (badone) [inline src/common/simple_spin.cc]: Nearly all the examples I found online include the memory barrier but I'll remove it as per your suggestion.

**Comment by badone** [comment]
Test this please

File: src/common/simple_spin.cc [hunk 3]
```diff
@@ -31,9 +28,11 @@ void simple_spin_lock(simple_spinlock_t *lock)
 	return;
     }
     // delay
-    for (int i = 0; i < 100000; i++) {
-      *foo = (*foo * 33) + 17;
-    }
+#if defined(__arm__) || defined(__aarch64)
```
Comment (tchaikov) [inline src/common/simple_spin.cc]: sorry, i meant `__aarch64__`. see https://sourceforge.net/p/predef/wiki/Architectures/

File: src/common/simple_spin.cc (hunk 1 above)
Comment (tchaikov) [inline src/common/simple_spin.cc]: @badone no, `defined()` is better in the sense that we are testing if they are `defined` or not. but C/C++ preprocessor evaluate the undefined macro to 0. so we don't need to change the `src/test/test_arch.cc`, unless we happen to touch them, and want to make them **look** better.

File: src/common/simple_spin.cc [hunk 4]
```diff
@@ -31,9 +28,11 @@ void simple_spin_lock(simple_spinlock_t *lock)
 	return;
     }
     // delay
-    for (int i = 0; i < 100000; i++) {
-      *foo = (*foo * 33) + 17;
-    }
+#if defined(__arm__) || defined(__aarch64__)
+    asm volatile("yield");
+#else
```
Comment (tchaikov) [inline src/common/simple_spin.cc]: we need to check for at least `#if defined(__i386__)` here, AFAIK, we do build on ppc64. in that case, it would be 

```c
  asm volatile("or 27,27,27");
```

and fallback to the `for` loop if we are compiling on none of them or just emit an error/warning at compile time. IMHO, the latter is acceptable in practice.

**Comment by badone** [comment]
@tchaikov how about this then?

File: src/common/simple_spin.cc [hunk 5]
```diff
@@ -31,9 +28,15 @@ void simple_spin_lock(simple_spinlock_t *lock)
 	return;
     }
     // delay
-    for (int i = 0; i < 100000; i++) {
-      *foo = (*foo * 33) + 17;
-    }
+#if defined(__i386_) || defined(__x86_64__)
```
Comment (tchaikov) [inline src/common/simple_spin.cc]: `__i386__`.

File: src/common/simple_spin.cc [hunk 6]
```diff
@@ -31,9 +28,15 @@ void simple_spin_lock(simple_spinlock_t *lock)
...
+    asm volatile("pause");
+#elif defined(__arm__) || defined(__aarch64__)
+    asm volatile("yield");
+#elif defined(__ppc64__)
+    asm volatile("or 27,27,27");
+#else
+    static_assert(false,"Unknown architecture");
```
Comment (tchaikov) [inline src/common/simple_spin.cc]: or just `#error "Unknown architecture"`. which can be handled by the preprocessor earlier. and you might want to add a space before `"`.

**Comment by badone** [comment]
@tchaikov @branch-predictor thanks for the help guys, sorry it was untidy.

File: src/common/simple_spin.cc (hunk 5 above)
Comment (tchaikov) [inline src/common/simple_spin.cc]: @badone it's not updated yet. you pushed a wrong commit?

**Comment by badone** [comment]
sigh... beat me by about 30 seconds... :(

**Comment by badone** [comment]
Test this please

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-03-31_17:31:21-rados-wip-kefu-testing---basic-smithi/

failed ones are fixed by #14274 and #14281

**Comment by smithfarm** [comment]
@badone Which architectures was this PR tested on? It appears to have broken the ppc64le and s390x builds. . .

**Comment by smithfarm** [comment]
The build error is:

```
[  672s] [ 33%] Building CXX object src/CMakeFiles/common-objs.dir/common/simple_spin.cc.o
[  672s] /home/abuild/rpmbuild/BUILD/ceph-12.0.1+git.1491313394.3372162/src/common/simple_spin.cc:38:2: error: #error "Unknown architecture"
[  672s]  #error "Unknown architecture"
[  672s]   ^
[  672s] src/CMakeFiles/common-objs.dir/build.make:2415: recipe for target 'src/CMakeFiles/common-objs.dir/common/simple_spin.cc.o' failed
[  672s] make[2]: *** [src/CMakeFiles/common-objs.dir/common/simple_spin.cc.o] Error 1
```

**Comment by smithfarm** [comment]
@badone Opened http://tracker.ceph.com/issues/19492

**Comment by badone** [comment]
@smithfarm only tested on x86_64 AFAIK. The problem with ppc should be fixed by #14310 I'm afraid I was unaware that anyone was seriously building in s390x so didn't really consider it... my bad, sorry.
