### PR TITLE
rados/objclass.h: fix build define CEPH_CLS_API in all cases

### PR DESCRIPTION
**Pull request by dalgaaf**
Fix for bug introduced with 096668ec5df93725a0726b53bbd30b4d4ab50f49:

In file included from src/objclass/objclass.h:13:0,
                 from src/cls/hello/cls_hello.cc:37:
src/include/rados/objclass.h:31:1: error: ‘CEPH_CLS_API’ does not name a
type; did you mean ‘CEPH_CAP_ANY’?
 CEPH_CLS_API void name##_cls_init()
 ^
/develop/ceph/source/ceph/src/include/rados/objclass.h:31:1: note: in
definition of macro ‘CLS_INIT’
 CEPH_CLS_API void name##_cls_init()
 ^~~~~~~~~~~~

Signed-off-by: Danny Al-Gaaf <danny.al-gaaf@bisect.de>

### CODE REVIEW

**Comment by joscollin** [comment]
@dalgaaf Thanks.

**Comment by markhpc** [comment]
FWIW, I can confirm that on my dev workstation, master fails to build using our normal build process without this commit applied.
