### PR TITLE
mgr/dashboard: Fix missing $event on deletion modal

### PR DESCRIPTION
**Pull request by ricardoasmarques**
This PR fixes the following frontend error:

`ERROR in src/app/shared/components/deletion-modal/deletion-modal.component.ts(78,5): error TS2554: Expected 1 arguments, but got 0.`

This error was introduces because of a "silent conflict" between:

- https://github.com/ceph/ceph/pull/20899
- https://github.com/ceph/ceph/pull/21529

Signed-off-by: Ricardo Marques <rimarques@suse.com>

### CODE REVIEW

**Comment by rjfd** [comment]
jenkins retest this please
