### PR TITLE
osd: implement hit_set_remove_all

### PR DESCRIPTION
**Pull request by wonzhq**
When hit set is not configured on startup or on a change, remove all previous hitsets.

### CODE REVIEW

**Comment by wonzhq** [comment]
@liewegas updated, pls take another look, thx!

**Comment by tchaikov** [comment]
LGTM. probably we should suggest user to disable hitset temporarily before upgrading to a version with #4941, otherwise the archived hit set objects will not be deleted.

**Comment by tchaikov** [comment]
@wonzhq i spotted some assertion failures in the rados qa run see http://qa-proxy.ceph.com/teuthology/ubuntu-2015-07-18_02:36:49-rados-wip-kefu-testing---basic-multi/978448/teuthology.log .

```
2015-07-19T04:13:04.792 INFO:tasks.workunit.client.0.plana25.stdout:[ RUN      ] LibRadosTwoPoolsPP.HitSetTrim
2015-07-19T04:13:11.944 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,0
2015-07-19T04:13:11.944 INFO:tasks.workunit.client.0.plana25.stdout:first is 1437304392
2015-07-19T04:13:12.953 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,0
2015-07-19T04:13:13.960 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,0
2015-07-19T04:13:14.972 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,0
2015-07-19T04:13:15.981 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,0
2015-07-19T04:13:16.988 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,0
2015-07-19T04:13:18.000 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,1437304397,1437304398,0
2015-07-19T04:13:19.008 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,1437304397,1437304398,0
2015-07-19T04:13:20.018 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,1437304397,1437304398,0
2015-07-19T04:13:21.029 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,1437304397,1437304398,1437304401,1437304402,0
2015-07-19T04:13:22.037 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,1437304397,1437304398,1437304401,1437304402,0
2015-07-19T04:13:23.044 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304392,1437304394,1437304395,1437304397,1437304398,1437304401,1437304402,0
2015-07-19T04:13:24.056 INFO:tasks.workunit.client.0.plana25.stdout: got ls 1437304395,1437304397,1437304398,1437304401,1437304402,1437304404,1437304405,0
2015-07-19T04:13:24.056 INFO:tasks.workunit.client.0.plana25.stdout:first now 1437304395, trimmed
2015-07-19T04:13:24.740 INFO:tasks.ceph.osd.5.burnupi19.stderr:osd/ReplicatedPG.cc: In function 'bool ReplicatedPG::is_degraded_or_backfilling_object(const hobject_t&)' thread 7f609f15a700 time 2015-07-19 04:13:24.733250
2015-07-19T04:13:24.741 INFO:tasks.ceph.osd.5.burnupi19.stderr:osd/ReplicatedPG.cc: 412: FAILED assert(!actingbackfill.empty())
2015-07-19T04:13:24.741 INFO:tasks.ceph.osd.5.burnupi19.stderr: ceph version 9.0.2-799-gba9c2ae (ba9c2ae4bffd3fd7b26a2e0ce843913b77940b8a)
2015-07-19T04:13:24.741 INFO:tasks.ceph.osd.5.burnupi19.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x8b) [0xc45d1b]
2015-07-19T04:13:24.741 INFO:tasks.ceph.osd.5.burnupi19.stderr: 2: ceph-osd() [0x88535d]
2015-07-19T04:13:24.742 INFO:tasks.ceph.osd.5.burnupi19.stderr: 3: (ReplicatedPG::hit_set_remove_all()+0x7c) [0x8b039c]
2015-07-19T04:13:24.742 INFO:tasks.ceph.osd.5.burnupi19.stderr: 4: (ReplicatedPG::on_pool_change()+0x161) [0x8b1a21]
2015-07-19T04:13:24.742 INFO:tasks.ceph.osd.5.burnupi19.stderr: 5: (PG::handle_advance_map(std::tr1::shared_ptr<OSDMap const>, std::tr1::shared_ptr<OSDMap const>, std::vector<int, std::allocator<int> >&, int, std::vector<int, std::allocator<int> >&, int, PG::RecoveryCtx*)+0x60c) [0x8348fc]
2015-07-19T04:13:24.743 INFO:tasks.ceph.osd.5.burnupi19.stderr: 6: (OSD::advance_pg(unsigned int, PG*, ThreadPool::TPHandle&, PG::RecoveryCtx*, std::set<boost::intrusive_ptr<PG>, std::less<boost::intrusive_ptr<PG> >, std::allocator<boost::intrusive_ptr<PG> > >*)+0x2c3) [0x6dcc73]
2015-07-19T04:13:24.743 INFO:tasks.ceph.osd.5.burnupi19.stderr: 7: (OSD::process_peering_events(std::list<PG*, std::allocator<PG*> > const&, ThreadPool::TPHandle&)+0x1f1) [0x6dd721]
2015-07-19T04:13:24.743 INFO:tasks.ceph.osd.5.burnupi19.stderr: 8: (OSD::PeeringWQ::_process(std::list<PG*, std::allocator<PG*> > const&, ThreadPool::TPHandle&)+0x18) [0x7328d8]
2015-07-19T04:13:24.743 INFO:tasks.ceph.osd.5.burnupi19.stderr: 9: (ThreadPool::worker(ThreadPool::WorkThread*)+0xa5e) [0xc3677e]
2015-07-19T04:13:24.743 INFO:tasks.ceph.osd.5.burnupi19.stderr: 10: (ThreadPool::WorkThread::entry()+0x10) [0xc37820]
2015-07-19T04:13:24.744 INFO:tasks.ceph.osd.5.burnupi19.stderr: 11: (()+0x8182) [0x7f60ba655182]
2015-07-19T04:13:24.744 INFO:tasks.ceph.osd.5.burnupi19.stderr: 12: (clone()+0x6d) [0x7f60b899afbd]
```

so at that very moment, the PG in question was still peering and the `actingbackfilling` was empty. probably we can only `hit_set_remove_all()` when the pg is active or peered. could you try the test locally?

**Comment by tchaikov** [comment]
http://tracker.ceph.com/issues/8193#change-55253 could be relevant .

**Comment by wonzhq** [comment]
@tchaikov sure, I'll take a look, and run it locally. Sorry for the trouble.

**Comment by wonzhq** [comment]
It appears that we'll hit this assertion failure for sure, since before the peering, `start_peering_interval` is called and it clears the `actingbackfill` set. Yep, we need to bypass the `is_degraded_or_backfilling_object` check when the PG is peering.

**Comment by tchaikov** [comment]
@wonzhq i am not sure if i understand what you mean by

> bypass the is_degraded_or_backfilling_object check when the PG is peering

i think, if PG is peering, we can not be sure if `hit_set_remove_all()` will clean up the hit_set archive objects on all OSDs of the PG. because we don't have a active PG at that moment, hence the safe bet would be to sit tight until `on_active()` gets called, which calls `hit_set_setup()` as well.

what do you think?

**Comment by wonzhq** [comment]
@tchaikov 

> i think, if PG is peering, we can not be sure if hit_set_remove_all() will clean up the hit_set archive objects on all OSDs of the PG. because we don't have an active PG at that moment

I'm not sure on this part. But I think you are correct. The PG doesn't have the acting set yet, it's unable to do the repop. So seems like the right solution is to return at the beginning of `hit_set_remove_all` if the PG is doing peering?

**Comment by tchaikov** [comment]
@wonzhq depending on how we check for the state. if we have something like

```
if (is_peered()) {
  // ..
}
```

i'd suggest put this condition in a higher level, i.e. in `hit_set_setup()`. as `hit_set_remove_all()` is more a function messing up with the `info.hit_set`.

**Comment by wonzhq** [comment]
@tchaikov FYI, I'm running into the same assert failure after making this change. I'll need to look more into this.

**Comment by tchaikov** [comment]
@wonzhq thanks for the update.

**Comment by wonzhq** [comment]
Seems like there is no relation between the PG state and `actingbackfill`. I see the PG state is active when running into this assert failure.

And I'm now guarding the `hit_set_remove_all` call with `if (!actingbackfill.emty())` in `hit_set_setup`, it passes the test.

**Comment by tchaikov** [comment]
> Seems like there is no relation between the PG state and actingbackfill. I see the PG state is active when running into this assert failure.

@wonzhq, then that OSD is likely a replica OSD.

> And I'm now guarding the `hit_set_remove_all` call with `if (!actingbackfill.emty())` in `hit_set_setup`, it passes the test.

but i think we should let the primary OSD to perform `hit_set_remove_all()`. which is probably the same as your approach, but in terms of semantic, it's could be easier to understand than `actingbackfill.emty()`.

what do you think?

**Comment by wonzhq** [comment]
@tchaikov yep, it's better to let the primary to do this. Thank you for pointing out this is a replica. I made the change and it passed this single teuthology test case in my local run.

**Comment by wonzhq** [comment]
Not sure what is causing the failure of the bot. But the 'make check' is successful when I run it locally.

**Comment by tchaikov** [comment]
LGTM after the qa run

**Comment by tchaikov** [comment]
it still fails the rados qa suite : http://pulpito.ceph.com/kchai-2015-08-06_10:03:50-rados-wip-kefu-testing---basic-multi/1002498/

**Comment by tchaikov** [comment]
```
   -10> 2015-08-06 15:15:27.479792 7faaab808700 10 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] state<Started/Primary/Peering>: Peering advmap
    -9> 2015-08-06 15:15:27.479797 7faaab808700 10 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] state<Started>: Started advmap
    -8> 2015-08-06 15:15:27.479802 7faaab808700 10 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] check_recovery_sources no source osds () went down
    -7> 2015-08-06 15:15:27.479809 7faaab808700 10 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] handle_activate_map
    -6> 2015-08-06 15:15:27.479814 7faaab808700  7 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] state<Started/Primary>: handle ActMap primary
    -5> 2015-08-06 15:15:27.479820 7faaab808700 15 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] publish_stats_to_osd 175: no change since
    -4> 2015-08-06 15:15:27.479825 7faaab808700 10 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] take_waiters
    -3> 2015-08-06 15:15:27.479830 7faaab808700 20 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] handle_activate_map: Not dirtying info: last_persisted is 175 while current is 198
    -2> 2015-08-06 15:15:27.479835 7faaab808700 10 osd.3 pg_epoch: 198 pg[0.13( empty local-les=175 n=0 ec=1 les/c 175/175 174/174/127) [3,1] r=0 lpr=175 crt=0'0 mlcod 0'0 peering] handle_peering_event: epoch_sent: 198 epoch_requested: 198 NullEvt
    -1> 2015-08-06 15:15:27.479841 7faaab808700 10 log is not dirty
     0> 2015-08-06 15:15:27.495443 7faaac009700 -1 osd/ReplicatedPG.cc: In function 'bool ReplicatedPG::is_degraded_or_backfilling_object(const hobject_t&)' thread 7faaac009700 time 2015-08-06 15:15:27.474611
osd/ReplicatedPG.cc: 412: FAILED assert(!actingbackfill.empty())
```
again, it was peering.

>  I see the PG state is active when running into this assert failure.

i doubt it. because `actingbackfill` is always set with acting osds (even stray ones) which are able to provide shards help to bring nodes updated.

**Comment by wonzhq** [comment]
@tchaikov FYI, I made a change and run 1/17 of the rados suite on our local teuthology cluster now. Since the cluster is not that powerful, this may take long time.

**Comment by tchaikov** [comment]
@wonzhq you could run the failed one first to see if it also fails in your environment first. and it can be reproduced, that would be helpful to improve this pull request.

**Comment by wonzhq** [comment]
@tchaikov our local cluster is not stable yet. I did the run yesterday, and got many unrelated errors. I think the cluster is just able to run a small number of jobs (say < 10) for now. I'm going to run just the failed one.

**Comment by tchaikov** [comment]
or you can run the failed one in sepia lab.

**Comment by wonzhq** [comment]
@tchaikov I've run this failed case in our local cluster. And yes, it failed with the assert error showing above.

Look closer into the code, I think it's because the PG is in the `Reset` state when calling the `hit_set_remove_all` function. `hit_set_remove_all` is called in `hit_set_setup`, and `hit_set_setup` is called in both `on_pool_change` and `on_activate`. However, `on_pool_change` is called when handling advance map, and the PG could be in the `Reset` state. `actingbackfill` is cleared in this case. This leads to the assert failure showing above. I think we should guard the `hit_set_remove_all` call with `(is_primary() && (is_active() || is_peered()))`.

I made the above change, and ran the teuthology test case again. It passed the test. Do you think I should run a subset of the rados suite on this PR to verify its correctness on the sepia lab?

**Comment by tchaikov** [comment]
> . I think we should guard the hit_set_remove_all call with `(is_primary() && (is_active() || is_peered()))`.

@wonzhq probably, we can simplify it with `(is_primary() && is_peered())`

```c++
  bool       is_peered() const {
    return state_test(PG_STATE_ACTIVE) || state_test(PG_STATE_PEERED);
  }
```

> I made the above change, and ran the teuthology test case again. It passed the test. Do you think I should run a subset of the rados suite on this PR to verify its correctness on the sepia lab?

it would be advisable to run a subset along with your other two needs-qa pull request #5453 and #5415 . but currently the master branch failed to compile on precise and centos6.5. so the qa run results include quite a few annoying noises. =(

the only concern is:

> I see the PG state is active when running into this assert failure.

are you still sure on this?

**Comment by wonzhq** [comment]
@tchaikov OK, I'll do the rados suite run together with #5453 and #5415. In order to run them on the sepia, I'll need to ask someone to create a branch in the ceph repository. Would this be ok?

Btw, for your concern on 'PG state is active when running into this assert failure', sorry it's a false observation.

**Comment by tchaikov** [comment]
@wonzhq so i assume you will go with
```c++
 (is_primary() && is_peered())
```

> In order to run them on the sepia, I'll need to ask someone to create a branch in the ceph repository. Would this be ok?

guess you are able to create a "wip-" branch already, no? i see we have `wip-intel-testing`.

**Comment by wonzhq** [comment]
Yes, I'll go with `(is_primary() && is_peered())`. And I don't have write permission of the ceph repo. Not sure if wip-intel-testing is used by someone, I'll take a look. Do you know 'the master branch failed to compile on precise and centos6.5' issue is temporary or has been there for long time? I can wait if it's temporary.

**Comment by tchaikov** [comment]
> And I don't have write permission of the ceph repo. 

i am happy to help if you want me to create a wip branch.

> Do you know 'the master branch failed to compile on precise and centos6.5' issue is temporary or has been there for long time? I can wait if it's temporary.

@wonzhq, just confirmed with sage, it's fixed already. only a few precise machines are leftover, they are locked by some developers. but i guess the signal/noise ratio is bearable now.

**Comment by wonzhq** [comment]
> i am happy to help if you want me to create a wip branch.

@tchaikov thanks! I can use the wip-intel-testing branch. Someone here has the write permission.

> just confirmed with sage, it's fixed already. only a few precise machines are leftover, they are locked by some developers. but i guess the signal/noise ratio is bearable now.

Great!

**Comment by tchaikov** [comment]
@wonzhq may i know how the test is going? we'd like to include this pull request in infernalis. if anything i can help with, feel free to ping me.

**Comment by wonzhq** [comment]
@tchaikov there were an error when I tried to start the teuthology run last week. After fixing that, I saw there were lots of queued jobs on sepia, so I didn't start the run. And the wip-intel-testing branch is used by someone else yesterday. I'll start the run today. Do you know when is the cut off date of Infernalis?

**Comment by tchaikov** [comment]
> there were an error when I tried to start the teuthology run last week. After fixing that, I saw there were lots of queued jobs on sepia, so I didn't start the run. 

yeah, i see. the sepia lab is overloaded. and i have trouble using my openstack teuthology env due to slow internet connection. still trying to figure out how to fix it.

> Do you know when is the cut off date of Infernalis?

@wonzhq very soon,  =) i have no exact date so far. will update you once i have it.

**Comment by wonzhq** [comment]
Done the teuthology testing on this PR. The results are at:
http://pulpito.ceph.com/yuan-2015-08-20_00:19:52-rados-wip-intel-testing---basic-multi/
http://pulpito.ceph.com/yuan-2015-08-20_19:40:11-rados-wip-intel-testing---basic-multi/

There is still an EC read assert failure. But I don't think it's relating to this PR.

**Comment by tchaikov** [comment]
yeah, there was a EIO on plana70, i checked the dmesg on it but failed to find any clue.

the one in yuan-2015-08-20_00:19:52-rados-wip-intel-testing---basic-multi/1024108 is :
```
2015-08-20 06:40:22.212419 7f99c6ff6700 -1 *** Caught signal (Segmentation fault) **
 in thread 7f99c6ff6700

 ceph version 9.0.1-940-g452ea14 (452ea14e34af7609c8d5079eb5c7fc0b6617b9bf)
 1: ceph-osd() [0xb4a71a]
 2: (()+0x10340) [0x7f99d674c340]
 3: (std::_Rb_tree<pg_shard_t, pg_shard_t, std::_Identity<pg_shard_t>, std::less<pg_shard_t>, std::allocator<pg_shard_t> >::equal_range(pg_shard_t const&)+0x10) [0x715de0]
 4: (std::_Rb_tree<pg_shard_t, pg_shard_t, std::_Identity<pg_shard_t>, std::less<pg_shard_t>, std::allocator<pg_shard_t> >::erase(pg_shard_t const&)+0x16) [0x715eb6]
 5: (ReplicatedBackend::op_commit(ReplicatedBackend::InProgressOp*)+0xb7) [0xa5a4e7]
 6: (Context::complete(int)+0x9) [0x6f5909]
 7: (ReplicatedPG::BlessedContext::finish(int)+0x94) [0x8e1944]
 8: (Context::complete(int)+0x9) [0x6f5909]
 9: (Finisher::finisher_thread_entry()+0x158) [0xb6f438]
 10: (()+0x8182) [0x7f99d6744182]
 11: (clone()+0x6d) [0x7f99d4caeefd]
```

@wonzhq it seems there are still some tests running, will you wait, or i am good to merge this pr. up to you. i am good either wise. 

LGTM.

**Comment by wonzhq** [comment]
@tchaikov 

> the one in yuan-2015-08-20_00:19:52-rados-wip-intel-testing---basic-multi/1024108 is weird enough, but does not look like relevant 

Yep, I don't think this one is relevant to this PR either. And the rerun of this test case is successful.

> it seems there are still some tests running, will you wait?

If you look into the teuthology log of the running/waiting ones, you'll see that either they hit the EC read assert failure or they failed to get enough machines. And all of them are EC test cases.

**Comment by tchaikov** [comment]
@wonzhq i am rerunning http://pulpito.ceph.com/yuan-2015-08-20_19:40:11-rados-wip-intel-testing---basic-multi/1024285/ at http://pulpito.ceph.com/kchai-2015-08-21_01:54:58-rados-master---basic-multi/ if it persists, we should file a ticket to track it.

i will kill the your jobs with assert error if you don't mind.

**Comment by tchaikov** [comment]
the build failed due to the merge, i am on it.
```
CXX osd/libosd_la-PGBackend.lo
osd/ReplicatedPG.cc: In member function 'void ReplicatedPG::hit_set_remove_all()':
error: osd/ReplicatedPG.cc:10597:45: no matching function for call to 'PG::Scrubber::write_blocked_by_scrub(hobject_t&)'
if (scrubber.write_blocked_by_scrub(aoid))
^
osd/ReplicatedPG.cc:10597:45: note: candidate is:
In file included from osd/ReplicatedPG.cc:19:0:
osd/PG.h:1166:10: note: bool PG::Scrubber::write_blocked_by_scrub(const hobject_t&, bool)
bool write_blocked_by_scrub(const hobject_t &soid, bool sort_bitwise) {
^
osd/PG.h:1166:10: note: candidate expects 2 arguments, 1 provided
CXX osd/libosd_la-HitSet.lo
```

**Comment by tchaikov** [comment]
#5632 is posted to fix the FTBFS.

**Comment by wonzhq** [comment]
Oh, sorry. I noticed there was a `write_blocked_by_scrub` call in `hit_set_persist` when doing rebase. But forgot there was also a call of it in the new function...

**Comment by tchaikov** [comment]
@wonzhq, =) it happens. 

BTW, http://pulpito.ceph.com/kchai-2015-08-21_01:54:58-rados-master---basic-multi/  also failed because it was unable to acquire free nodes

```
2015-08-22T13:56:47.919 INFO:teuthology.task.internal:waiting for more plana,burnupi,mira machines to be free (need 5 + 4, have 5)...
```

it's not a bug but we will always suffer from it in a highly loaded test bed when running tests involving more machines.

**Comment by tchaikov** [comment]
@wonzhq, seems the tested branch only has this pull request?

**Comment by wonzhq** [comment]
@tchaikov yes, it only has this PR. To avoid noises from other PRs.
