### PR TITLE
mgr: initialize PyModuleRegistry sooner

### PR DESCRIPTION
**Pull request by jcsp**
This was waiting on MgrMap to init, so that it would know whether
modules should be enabled.  However, you don't really need to know
that until someone calls standby_start or active_start, so we
can initialize during MgrStandby::init, and fill out the enabled
flags later.

This prevents the mgr from prematurely emitting a MMgrBeacon
that claims no modules are found.

http://tracker.ceph.com/issues/22918
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
ref http://tracker.ceph.com/issues/22919?

**Comment by yuriw** [comment]
Seems to have conflict

From https://github.com/jcsp/ceph
 * branch            wip-22918  -> FETCH_HEAD
warning: Failed to merge submodule src/rocksdb (not checked out)
CONFLICT (rename/add): Rename src/test/ubuntu-12.04/Dockerfile.in->src/test/rbd-ggate.sh in f88a2bdfd414be49fff62ece6b7d7defdbd1ca10. src/test/rbd-ggate.sh added in HEAD

**Comment by jcsp** [comment]
Sorry, I had a total brainfart and opened this PR instead of the one I meant to open as a backport -- this is not even a backport at all!

**Comment by jcsp** [comment]
OK, finally came back to this and fixed it up, should be good to go.  Passed locally with tasks.mgr.test_module_selftest

File: src/mgr/PyModuleRegistry.h [hunk 1]
```diff
@@ -81,26 +81,42 @@ class PyModuleRegistry
...
-
-    if (standby_modules != nullptr) {
-      standby_modules->handle_mgr_map(mgr_map_);
+    if (mgr_map.epoch == 0) {
+      // First time we see MgrMap, set the enabled flags on modules
+      // This should always happen before someone calls standby_start
+      // or active_start
+      for (const auto &i : modules) {
+        const auto &module = i.second;
+        const bool enabled = (mgr_map.modules.count(module_name) > 0);
```
Comment (tchaikov) [inline src/mgr/PyModuleRegistry.h]:
```
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.0.1-2432-g7c5dfdf/rpm/el7/BUILD/ceph-13.0.1-2432-g7c5dfdf/src/mgr/PyModuleRegistry.h:97:53: error: 'module_name' was not declared in this scope
         const bool enabled = (mgr_map.modules.count(module_name) > 0);
                                                     ^~~~~~~~~~~
```

Comment (tchaikov) [reply src/mgr/PyModuleRegistry.h]: could also put following, as we have structured binding in C++17 now:
```c++
for (auto& [module_name, module] : modules) {
  const bool enabled = (mgr_map.modules.count(module_name) > 0);
  module.set_enabled(enabled);
}
```

please note `PyModule::set_enabled()` is not a const method. so we cannot use `const auto& [module_name, module]` here.

Comment (jcsp) [reply src/mgr/PyModuleRegistry.h]: Thanks for suggestions, this is my first time using the new structured binding bits and I like it :-)

The `const auto` is permitted (if a bit misleading) because the `module` part is a shared_ptr rather than the actual PyModule

I've pushed an update.

**Comment by jcsp** [comment]
@tchaikov could you do one last review pass when you have a minute?

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-03-14_04:42:43-rados-wip-kefu-testing-2018-03-14-1106-distro-basic-mira/

- SLOW_OPS failures are introduced by #20660
- the coredump is addressed by #20909
