### PR TITLE
mgr/cephadm : Verify MTU configuration before adding hosts to the bootstrapped cluster

### PR DESCRIPTION
**Pull request by djagdale4**
fixes : https://tracker.ceph.com/issues/80384

## Description :

Add MTU validation to `ceph orch host add` to detect MTU mismatches before adding a new host.

The validation performs a **DF ICMP ping** from the active manager host using its MTU to verify that the new host can support the same packet size without fragmentation.

This prevents adding hosts with incompatible MTU configurations to the Ceph cluster.

---
#### Before : 

```
[root@ceph-node-00 ~]# nmcli device show ens3 | grep MTU
GENERAL.MTU:                            9000
[root@ceph-node-00 ~]#
logout


[root@ceph-node-01 ~]# nmcli device show ens3 | grep MTU
GENERAL.MTU:                            1500
[root@ceph-node-01 ~]#
[root@ceph-node-01 ~]#
logout


[root@ceph-node-00 ~]# cephadm shell
Inferring fsid 173fe042-aba6-11f1-9523-525400bcb25b
Inferring config /var/lib/ceph/173fe042-aba6-11f1-9523-525400bcb25b/mon.ceph-node-00/config
[ceph: root@ceph-node-00 /]# ceph orch host add ceph-node-01 192.168.100.101
Added host 'ceph-node-01' with addr '192.168.100.101'
[ceph: root@ceph-node-00 /]#
[ceph: root@ceph-node-00 /]#
[ceph: root@ceph-node-00 /]#
[ceph: root@ceph-node-00 /]#
[ceph: root@ceph-node-00 /]# ceph orch host ls
HOST          ADDR             LABELS  STATUS
ceph-node-00  192.168.100.100  _admin
ceph-node-01  192.168.100.101
3 hosts in cluster
[ceph: root@ceph-node-00 /]#
```

#### After 

```
[root@ceph-node-00 ~]# nmcli device show ens3 | grep MTU
GENERAL.MTU:                            9000
[root@ceph-node-00 ~]# exit
logout
djagdale:src$ kcli ssh -u root -- ceph-node-02
Last login: Mon Sep  7 06:24:02 2026 from 192.168.100.1
[root@ceph-node-02 ~]# nmcli device show ens3 | grep MTU
GENERAL.MTU:                            1500
[root@ceph-node-02 ~]# exit
logout
djagdale:src$ kcli ssh -u root -- ceph-node-00
Last login: Mon Sep  7 06:28:43 2026 from 192.168.100.1
[systemd]
Failed Units: 1
  cloud-final.service
[root@ceph-node-00 ~]# cephadm shell
Inferring fsid 427dd516-aa7a-11f1-9a2a-5254006c713e
Inferring config /var/lib/ceph/427dd516-aa7a-11f1-9a2a-5254006c713e/mon.ceph-node-00/config
[ceph: root@ceph-node-00 /]# ceph orch host add ceph-node-02 192.168.100.102
Error EINVAL: MTU check failed for ceph-node-02 (192.168.100.102): Non-zero exit code 1 from /usr/bin/ping -4 -M do -s 8972 -c 1 -W 2 192.168.100.102
/usr/bin/ping: stdout PING 192.168.100.102 (192.168.100.102) 8972(9000) bytes of data.
/usr/bin/ping: stdout
/usr/bin/ping: stdout --- 192.168.100.102 ping statistics ---
/usr/bin/ping: stdout 1 packets transmitted, 0 received, 100% packet loss, time 0ms
/usr/bin/ping: stdout
ERROR: MTU validation failed for host 192.168.100.102. Could not send 9000 byte packet without fragmentation. PING 192.168.100.102 (192.168.100.102) 8972(9000) bytes of data.

--- 192.168.100.102 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
Use --skip-mtu-check to add anyway.
[ceph: root@ceph-node-00 /]# ceph orch host ls
HOST          ADDR             LABELS  STATUS
ceph-node-00  192.168.100.100  _admin
1 hosts in cluster
[ceph: root@ceph-node-00 /]# ceph orch host add ceph-node-02 192.168.100.102 --skip-mtu-check
Added host 'ceph-node-02' with addr '192.168.100.102'
[ceph: root@ceph-node-00 /]# ceph orch host ls
HOST          ADDR             LABELS  STATUS
ceph-node-00  192.168.100.100  _admin
ceph-node-02  192.168.100.102
2 hosts in cluster
```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test classic perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-classic/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml)
- `jenkins test crimson perf` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-perf-crimson/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml)
- `jenkins test signed` [Jenkins Job](https://jenkins.ceph.com/job/ceph-pr-commits/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pr-commits/config/definitions/ceph-pr-commits.yml)
- `jenkins test make check` [Jenkins Job](https://jenkins.ceph.com/job/ceph-pull-requests/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pull-requests/config/definitions/ceph-pull-requests.yml)
- `jenkins test make check arm64` [Jenkins Job](https://jenkins.ceph.com/job/ceph-pull-requests-arm64/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml)
- `jenkins test submodules` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-pr-submodules/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pr-submodules/config/definitions/ceph-pr-commits.yml)
- `jenkins test dashboard` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-dashboard-pull-requests/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml)
- `jenkins test dashboard cephadm` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-dashboard-cephadm-e2e/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-dashboard-cephadm-e2e/config/definitions/ceph-dashboard-cephadm-e2e.yml)
- `jenkins test api` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-api/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-pr-api/config/definitions/ceph-pr-api.yml)
- `jenkins test docs` [ReadTheDocs](https://readthedocs.org/projects/ceph/) | [Github Workflow Definition](https://github.com/ceph/ceph/blob/main/.readthedocs.yml)
- `jenkins test ceph-volume all` [Jenkins Jobs](https://jenkins.ceph.com/view/ceph-volume%20PR/) | [Jenkins Jobs Definition](https://github.com/ceph/ceph-build/blob/main/ceph-volume-cephadm-prs/config/definitions/ceph-volume-pr.yml)
- `jenkins test windows` [Jenkins Job](https://jenkins.ceph.com/job/ceph-windows-pull-requests/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml)
- `jenkins test rook e2e` [Jenkins Job](https://jenkins.ceph.com/view/all/job/ceph-orchestrator-rook-e2e/) | [Jenkins Job Definition](https://github.com/ceph/ceph-build/blob/main/ceph-rook-e2e/config/definitions/ceph-orchestrator-rook-e2e.yml)

You must only issue one Jenkins command per-comment. Jenkins does not understand
comments with more than one command.
</details>

### CODE REVIEW

File: src/cephadm/cephadm.py [hunk 1]
```diff
@@ -4581,6 +4581,68 @@ def command_check_host(ctx: CephadmContext) -> None:
...
+    cmd = [ping_bin, '-6' if ipv6 else '-4', '-M', 'do', '-s', str(payload_size),
+           '-c', '1', '-W', '2', addr]
+    out, err, code = call(ctx, cmd, verbosity=CallVerbosity.QUIET_UNLESS_ERROR)
+    if code:
+        overhead = 48 if ipv6 else 28
+        raise Error(
+            f'MTU validation failed for host {addr}. '
+            f'Could not send {payload_size + overhead} byte packet without fragmentation. '
+            f'{err or out}'
+        )
```
Comment (guits) [inline src/cephadm/cephadm.py:4644]: there is no reason to prefix these functions with a "_"

File: src/cephadm/cephadm.py [hunk 2]
```diff
@@ -4581,6 +4581,68 @@ def command_check_host(ctx: CephadmContext) -> None:
...
+    cmd = ['ip', '-6', 'route', 'get', addr] if ipv6 else ['ip', 'route', 'get', addr]
+    out, err, code = call(ctx, cmd, verbosity=CallVerbosity.QUIET_UNLESS_ERROR)
+    if code:
+        raise Error(f'Unable to determine source interface to reach {addr}: {err or out}')
+    m = re.search(r'\bdev\s+(\S+)', out)
+    if not m:
+        raise Error(f'Unable to determine source interface to reach {addr}')
+    if 'local' in out.split() or m.group(1) == 'lo':
+        return 'lo'
+    return m.group(1)
```
Comment (guits) [inline src/cephadm/cephadm.py:4617]: this scrapes human readable output with a regex, this is the kind of bad practice I avoid as much as possible. `ip` supports json output (-j) so please use it.

File: src/pybind/mgr/cephadm/module.py [hunk 3]
```diff
@@ -2283,6 +2312,9 @@ def _add_host(self, spec):
         if spec.addr == spec.hostname and ip_addr:
             spec.addr = ip_addr
 
+        skip_mtu_check = bool(getattr(spec, 'skip_mtu_check', False))
```
Comment (guits) [inline src/pybind/mgr/cephadm/module.py:2315]: it means that '--skip-mtu-check' is smuggled into HostSpec with setattr/getattr.

it is not a real API and it will not survive json because HostSpec has no field 'skip_mtu_check' so to_json() / from_json() will drop it

File: src/cephadm/cephadm.py [hunk 4]
```diff
@@ -4581,6 +4581,68 @@ def command_check_host(ctx: CephadmContext) -> None:
...
+    logger.info('MTU check OK for %s via %s (mtu=%s)', target_ip, iface, mtu)
+    return 0
+
+
+def _get_route_interface(ctx: CephadmContext, addr: str, ipv6: bool) -> str:
+    cmd = ['ip', '-6', 'route', 'get', addr] if ipv6 else ['ip', 'route', 'get', addr]
+    out, err, code = call(ctx, cmd, verbosity=CallVerbosity.QUIET_UNLESS_ERROR)
+    if code:
+        raise Error(f'Unable to determine source interface to reach {addr}: {err or out}')
+    m = re.search(r'\bdev\s+(\S+)', out)
```
Comment (guits) [inline src/cephadm/cephadm.py:4612]: this is tied to iproute2 text formatting

File: src/pybind/mgr/cephadm/module.py [hunk 5]
```diff
@@ -2217,6 +2211,41 @@ def _check_valid_addr(self, host: str, addr: str) -> str:
...
+        """Don't-fragment ping from the active mgr host to the new host, using the mgr host MTU."""
+        if skip_mtu_check:
+            return
+        dest_ip = addr
+        try:
+            dest_ip = utils.resolve_ip(addr)
+            if ipaddress.ip_address(dest_ip).is_loopback:
+                return
+        except (OrchestratorError, ValueError):
+            pass
```
Comment (guits) [inline src/pybind/mgr/cephadm/module.py:2224]: if resolve_ip() fails this try/except drops the dns error and it keeps the original hostname in dest_ip.
it means that check-mtu will fail and the user will never see the real lookup failure.

i think we should reraise the OrchestratorError from resolve_ip() or (or skip the MTU check on purpose and log why?)

File: src/cephadm/cephadm.py [hunk 6]
```diff
@@ -4581,6 +4581,68 @@ def command_check_host(ctx: CephadmContext) -> None:
...
+    if not m:
+        raise Error(f'Unable to determine source interface to reach {addr}')
```
Comment (guits) [inline src/cephadm/cephadm.py:4614]: if code: raise then re.search then another almost identical raise, this is two error paths for the same thing

**Review by guits — CHANGES_REQUESTED** [review]

File: src/pybind/mgr/cephadm/module.py (hunk 5 above)
Comment (djagdale4) [reply src/pybind/mgr/cephadm/module.py]: Updated the code to propagate the OrchestratorError from resolve_ip() so the user sees the actual address resolution failure.

File: src/cephadm/cephadm.py (hunk 1 above)
Comment (djagdale4) [reply src/cephadm/cephadm.py]: Removed the _ prefix from these  functions as suggested.

File: src/cephadm/cephadm.py (hunk 2 above)
Comment (djagdale4) [reply src/cephadm/cephadm.py]: Updated the code to use `ip -j` and parse the JSON output instead of relying on regex parsing.

File: src/pybind/mgr/cephadm/module.py (hunk 3 above)
Comment (djagdale4) [reply src/pybind/mgr/cephadm/module.py]: Updated add_host() to pass skip_mtu_check explicitly as a parameter instead of storing it in HostSpec via setattr/getattr

File: src/cephadm/cephadm.py (hunk 4 above)
Comment (djagdale4) [reply src/cephadm/cephadm.py]: Updated the code to use `ip -j` JSON output instead of relying on iproute2 text formatting.

File: src/cephadm/cephadm.py (hunk 6 above)
Comment (djagdale4) [reply src/cephadm/cephadm.py]: Updated the error handling to provide clear, specific errors for command and route parsing failures instead of using two nearly identical error paths.
