### PR TITLE
rgw/multisite:  include request body when CreateBucket op is forwarded to master

### PR DESCRIPTION
**Pull request by smanjara**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
cc @clwluvw

**Comment by clwluvw** [comment]
Can you please take a look at https://github.com/ceph/ceph/pull/59305? I believe there is more about it.

**Comment by cbodley** [comment]
> Can you please take a look at #59305? I believe there is more about it.

if we're forwarding the same request body, we shouldn't need to mess with content-sha256 or re-sign the request. maybe you can suggest a test case to show what's missing here?

**Comment by clwluvw** [comment]
There are two different sides to the problem. One is about the behavior of  `RGWRESTSimpleRequest::forward_request` when the body is null or needs a re-sign and one is regarding the create bucket which uses the forwarded `rgwx-` header for location param https://github.com/ceph/ceph/blob/37e0285de0606cb2a69106d15df94b0100be1ddf/src/rgw/rgw_op.cc#L3477-L3481
This PR eliminates the fact that the body is empty and the signature is mismatched but the other problems of the mentioned code and when it needs to be re-sign (I faced that in delete I guess) and when the body is empty (which probably with this PR we don't have the case but can be fixed generally as the logic) are still there.

**Comment by clwluvw** [comment]
FYI, another issue on bucket creation: https://github.com/ceph/ceph/pull/60254

File: src/test/rgw/rgw_multi/tests.py [hunk 1]
```diff
@@ -3634,4 +3634,17 @@ def test_copy_object_different_bucket():
...
     zonegroup_bucket_checkpoint(zonegroup_conns, dest_bucket.name)
+
+
+def test_bucket_location_constraint():
+    zonegroup = realm.master_zonegroup()
+    zonegroup_conns = ZonegroupConns(zonegroup)
+    primary = zonegroup_conns.rw_zones[0]
+    secondary = zonegroup_conns.rw_zones[1]
+
+    bucket_name = secondary.create_bucket(gen_bucket_name(), location=zonegroup)
```
Comment (clwluvw) [inline src/test/rgw/rgw_multi/tests.py:3645]:
```suggestion
    bucket = secondary.create_bucket(gen_bucket_name(), location=zonegroup)
```

File: src/test/rgw/rgw_multi/tests.py [hunk 2]
```diff
@@ -3634,4 +3634,17 @@ def test_copy_object_different_bucket():
...
+    log.debug('created bucket=%s', bucket.name)
+    
+    assert primary.get_bucket(bucket_name)
```
Comment (clwluvw) [inline src/test/rgw/rgw_multi/tests.py:3648]:
```suggestion
    assert primary.get_bucket(bucket.name)
```

**Comment by mattbenjamin** [comment]
@shilpa are you going to approve this?  It is in use downstream.

**Comment by clwluvw** [comment]
jenkins test make check arm64

**Comment by cbodley** [comment]
> > @shilpa are you going to approve this? It is in use downstream.
> 
> @mattbenjamin wasn't happy with the test I added. but i guess it'll do.
> 
> scheduled a run https://pulpito.ceph.com/smanjara-2024-11-19_20:26:15-rgw:multisite-wip-fix-missing-http-data-test-distro-default-smithi/

```
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:rgw_multi.tests.test_bucket_location_constraint ... ERROR
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:======================================================================
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:ERROR: rgw_multi.tests.test_bucket_location_constraint
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:----------------------------------------------------------------------
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:Traceback (most recent call last):
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:  File "/home/teuthworker/src/git.ceph.com_teuthology_029bda193b1d38b67b279eb5c1037caa8408be24/virtualenv/lib/python3.10/site-packages/nose/case.py", line 170, in runTest
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:    self.test(*self.arg)
2024-11-19T21:15:47.660 INFO:tasks.rgw_multisite_tests:  File "/home/teuthworker/src/git.ceph.com_ceph-c_48505f3628a7c7a5f9e063923577af58ccacb8ce/qa/../src/test/rgw/rgw_multi/tests.py", line 3646, in test_bucket_location_constraint
2024-11-19T21:15:47.661 INFO:tasks.rgw_multisite_tests:    bucket = secondary.create_bucket(gen_bucket_name(), location=zonegroup)
2024-11-19T21:15:47.661 INFO:tasks.rgw_multisite_tests:TypeError: RadosZone.Conn.create_bucket() got an unexpected keyword argument 'location'
```

**Comment by clwluvw** [comment]
> i opened https://tracker.ceph.com/issues/69281 for backports to reef and squid

I guess reef is immune from this as this was a regression by https://github.com/ceph/ceph/pull/50599 that hasn't been backported to reef if I'm not mistaken.

**Comment by cbodley** [comment]
> I guess reef is immune from this as this was a regression by #50599 that hasn't been backported to reef if I'm not mistaken.

thanks, updated the tracker

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/148473/
> The following tests FAILED:
	248 - unittest_rbd_mirror (SEGFAULT)

looks like https://tracker.ceph.com/issues/63798 or https://tracker.ceph.com/issues/53959

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/148481/
> The following tests FAILED:
	 31 - run-rbd-unit-tests-1.sh (Failed)

commented on https://tracker.ceph.com/issues/46875

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
@smanjara https://github.com/ceph/ceph/pull/52791 has a more detailed test case for bucket location. can you please remove the test changes from this PR so i can test/merge the two PRs together?

**Review by cbodley — APPROVED** [review]

File: src/test/rgw/rgw_multi/tests.py [hunk 3]
```diff
@@ -3634,4 +3634,4 @@ def test_copy_object_different_bucket():
         CopySource = source_bucket.name + '/' + objname)
     
     zonegroup_bucket_checkpoint(zonegroup_conns, dest_bucket.name)
-    
+
```
Comment (cbodley) [inline src/test/rgw/rgw_multi/tests.py:3637]: this whitespace change conflicts with https://github.com/ceph/ceph/pull/52791

Comment (smanjara) [reply src/test/rgw/rgw_multi/tests.py]: done

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2025-01-08_19:44:28-rgw-wip-69281-distro-default-smithi/ (batched with https://github.com/ceph/ceph/pull/52791)
