### PR TITLE
cmake: define BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT for rgw tests

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise unittest_rbd_mirror does not compile with boost v1.75

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Review by cbodley — APPROVED** [review]
> otherwise unittest_rbd_mirror does not compile with boost v1.75

was this a typo? unittest_rbd_mirror is in test/rbd_mirror/CMakeLists.txt

i don't object to adding this to test/rgw also, but maybe we're better off moving this to src/CMakeLists.txt instead of copying it to several subdirectories

**Comment by tchaikov** [comment]
sorry, it was a type
```
FAILED: src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/test_rgw_dmclock_scheduler.cc.o
/usr/bin/ccache /usr/bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_CHRONO_DYN_LINK -DBOOST_CONTEXT_DYN_LINK -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_COROUTINE_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_RANDOM_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__ -Isrc/include -I../src -I../src/dmclock/src -I../src/dmclock/support/src -I../src/spawn/include -isystem /opt/ceph/include -isystem include -isystem ../src/xxHash -isystem ../src/rapidjson/include -isystem ../src/fmt/include -isystem ../src/googletest/googlemock/include -isystem ../src/googletest/googlemock -isystem ../src/googletest/googletest/include -isystem ../src/googletest/googletest -g -fPIE   -Wall -fno-strict-aliasing -fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith -Werror=format-security -Winit-self -Wno-unknown-pragmas -Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024 -Wpessimizing-move -Wredundant-move -Wstrict-null-sentinel -Woverloaded-virtual -fno-new-ttp-matching -DCEPH_DEBUG_MUTEX -fstack-protector-strong -D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -std=c++17 -MD -MT src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/test_rgw_dmclock_scheduler.cc.o -MF src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/test_rgw_dmclock_scheduler.cc.o.d -o src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/test_rgw_dmclock_scheduler.cc.o -c ../src/test/rgw/test_rgw_dmclock_scheduler.cc
In file included from ../src/rgw/rgw_dmclock_async_scheduler.h:18,
                 from ../src/test/rgw/test_rgw_dmclock_scheduler.cc:18:
../src/common/async/completion.h: In instantiation of ‘void ceph::async::detail::CompletionImpl<Executor1, Handler, T, Args>::destroy_defer(std::tuple<Args ...>&&) [with Executor1 = boost::asio::io_context::basic_executor_type<std::allocator<void>, 0>; Handler = boost::asio::detail::coro_handler<boost::asio::executor_binder<void (*)(), boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > > >, crimson::dmclock::PhaseType>; T = ceph::async::AsBase<rgw::dmclock::Request>; Args = {boost::system::error_code, crimson::dmclock::PhaseType}]’:
../src/common/async/completion.h:188:8:   required from here
../src/common/async/completion.h:194:29: error: ‘boost::asio::executor_work_guard<boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > >, void>::executor_type’ {aka ‘class boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > >’} has no member named ‘defer’; did you mean ‘prefer’?
  194 |     w.second.get_executor().defer(std::move(f), alloc2);
../src/common/async/completion.h: In instantiation of ‘void ceph::async::detail::CompletionImpl<Executor1, Handler, T, Args>::destroy_dispatch(std::tuple<Args ...>&&) [with Executor1 = boost::asio::io_context::basic_executor_type<std::allocator<void>, 0>; Handler = boost::asio::detail::coro_handler<boost::asio::executor_binder<void (*)(), boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > > >, crimson::dmclock::PhaseType>; T = ceph::async::AsBase<rgw::dmclock::Request>; Args = {boost::system::error_code, crimson::dmclock::PhaseType}]’:
../src/common/async/completion.h:196:8:   required from here
../src/common/async/completion.h:202:29: error: ‘boost::asio::executor_work_guard<boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > >, void>::executor_type’ {aka ‘class boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > >’} has no member named ‘dispatch’
  202 |     w.second.get_executor().dispatch(std::move(f), alloc2);
../src/common/async/completion.h: In instantiation of ‘void ceph::async::detail::CompletionImpl<Executor1, Handler, T, Args>::destroy_post(std::tuple<Args ...>&&) [with Executor1 = boost::asio::io_context::basic_executor_type<std::allocator<void>, 0>; Handler = boost::asio::detail::coro_handler<boost::asio::executor_binder<void (*)(), boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > > >, crimson::dmclock::PhaseType>; T = ceph::async::AsBase<rgw::dmclock::Request>; Args = {boost::system::error_code, crimson::dmclock::PhaseType}]’:
../src/common/async/completion.h:204:8:   required from here
../src/common/async/completion.h:210:29: error: ‘boost::asio::executor_work_guard<boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > >, void>::executor_type’ {aka ‘class boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > >’} has no member named ‘post’
  210 |     w.second.get_executor().post(std::move(f), alloc2);
[31/48] Building CXX object src/test/rgw/CMakeFiles/unittest_rgw_iam_policy.dir/test_rgw_iam_policy.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by cbodley** [comment]
gotcha, thanks @tchaikov!

**Comment by tchaikov** [comment]
> > otherwise unittest_rbd_mirror does not compile with boost v1.75
> 
> was this a typo? unittest_rbd_mirror is in test/rbd_mirror/CMakeLists.txt
> 
> i don't object to adding this to test/rgw also, but maybe we're better off moving this to src/CMakeLists.txt instead of copying it to several subdirectories

i was thinking about this. but i wanted to make this explicit that this definition is attached to Boost::asio. but neither Boost nor CMake defines Boost::asio library. so, if we want to go this way, we would need to *add* a library. i can do this in a follow-up PR, if you think it's the way to go.

**Comment by cbodley** [comment]
right, since it's a header-only library we include it without needing a target. we could add a target for this definition, but since it's not required to compile/link it'd be easy to forget adding the dependency to new targets

i was suggesting that we put this `add_definitions()` at the top-level to apply globally to all targets. that's not ideal either, but it does give us full coverage - i'll defer to your judgement here

someday, we'll convert our stuff to use the std executors and we can drop this

**Comment by tchaikov** [comment]
> someday, we'll convert our stuff to use the std executors and we can drop this

how about s/someday/next Monday/ ? i plan to upgrade libboost in master to 1.75.

**Comment by cbodley** [comment]
> > someday, we'll convert our stuff to use the std executors and we can drop this
> 
> how about s/someday/next Monday/ ? actually, i also investigated this option. it's non-trivial, but not that scary. i plan to upgrade libboost in master to 1.75.

i raised this for discussion on dev@ceph.io, see "boost 1.74 and BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT"

**Comment by cbodley** [comment]
> i plan to upgrade libboost in master to 1.75

cool, i think that makes your strategy of a `Boost::asio` target more attractive - since, if we forget to add it to a new target, we know it will fail to compile
