### PR TITLE
luminous: DaemonState members accessed outside of locks

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21524

### CODE REVIEW

**Comment by shinobu-x** [comment]
Conflict from 806f108

```
--- a/src/mgr/ActivePyModules.cc
+++ b/src/mgr/ActivePyModules.cc
@@@ -603,6 -749,8 +603,11 @@@ PyObject* ActivePyModules::get_perf_sch
    }

    PyFormatter f;
++<<<<<<< HEAD:src/mgr/ActivePyModules.cc
++=======
+   f.open_object_section("perf_schema");
+ 
++>>>>>>> 806f108... mgr: clean up DaemonStateIndex locking:src/mgr/PyModules.cc
    if (!daemons.empty()) { 
      for (auto statepair : daemons) {
        auto key = statepair.first;
@@@ -613,10 -761,9 +618,16 @@@
        f.open_object_section(daemon_name.str().c_str());
        
        Mutex::Locker l(state->lock);
++<<<<<<< HEAD:src/mgr/ActivePyModules.cc
 +      for (auto ctr_inst_iter : state->perf_counters.instances) {
 +        const auto &counter_name = ctr_inst_iter.first;
 +      f.open_object_section(counter_name.c_str());
 +      auto type = state->perf_counters.types[counter_name];
++=======
+       for (auto typestr : state->perf_counters.declared_types) {
+       f.open_object_section(typestr.c_str());
+       auto type = state->perf_counters.types[typestr];
++>>>>>>> 806f108... mgr: clean up DaemonStateIndex locking:src/mgr/PyModules.cc
        f.dump_string("description", type.description);
        if (!type.nick.empty()) {
          f.dump_string("nick", type.nick);
```

**Comment by shinobu-x** [comment]
Conflict from 64af9d3

```
--- a/src/mgr/DaemonServer.cc
+++ b/src/mgr/DaemonServer.cc
@@@ -276,36 -276,31 +276,45 @@@ bool DaemonServer::ms_dispatch(Message
  
  void DaemonServer::maybe_ready(int32_t osd_id)
  {
++<<<<<<< HEAD
 +  if (pgmap_ready.load()) {
 +    // Fast path: we don't need to take lock because pgmap_ready
 +    // is already set
 +  } else {
 +    Mutex::Locker l(lock);
++=======
+   Mutex::Locker l(lock);
+   
+   if (!pgmap_ready && reported_osds.find(osd_id) == reported_osds.end()) {
+     dout(4) << "initial report from osd " << osd_id << dendl;
+     reported_osds.insert(osd_id);
+     std::set<int32_t> up_osds;
++>>>>>>> 64af9d3... mgr/DaemonServer: handle MMgrReports in parallel
  
 -    cluster_state.with_osdmap([&](const OSDMap& osdmap) {
 -        osdmap.get_up_osds(up_osds);
 -    }); 
 +    if (reported_osds.find(osd_id) == reported_osds.end()) {
 +      dout(4) << "initial report from osd " << osd_id << dendl;
 +      reported_osds.insert(osd_id);
 +      std::set<int32_t> up_osds;
        
 -    std::set<int32_t> unreported_osds;
 -    std::set_difference(up_osds.begin(), up_osds.end(),
 -                        reported_osds.begin(), reported_osds.end(),
 -                        std::inserter(unreported_osds, unreported_osds.begin()));                      
 +      cluster_state.with_osdmap([&](const OSDMap& osdmap) {
 +          osdmap.get_up_osds(up_osds);
 +      }); 
        
 -    if (unreported_osds.size() == 0) {
 -      dout(4) << "all osds have reported, sending PG state to mon" << dendl;
 -      pgmap_ready = true;
 -      reported_osds.clear();
 -      // Avoid waiting for next tick
 -      send_report();
 -    } else {
 -      dout(4) << "still waiting for " << unreported_osds.size() << " osds"
 -                 " to report in before PGMap is ready" << dendl;
 +      std::set<int32_t> unreported_osds;
 +      std::set_difference(up_osds.begin(), up_osds.end(),
 +                          reported_osds.begin(), reported_osds.end(),
 +                          std::inserter(unreported_osds, unreported_osds.begin()));                      
 +
 +      if (unreported_osds.size() == 0) {
 +        dout(4) << "all osds have reported, sending PG state to mon" << dendl;
 +        pgmap_ready = true;
 +        reported_osds.clear();
 +        // Avoid waiting for next tick
 +        send_report();
 +      } else {
 +        dout(4) << "still waiting for " << unreported_osds.size() << " osds"
 +                   " to report in before PGMap is ready" << dendl;
 +      }            
      }
    } 
  }
```

**Comment by shinobu-x** [comment]
Conflict from d209157

```
--- a/src/mgr/DaemonServer.cc
+++ b/src/mgr/DaemonServer.cc
@@@ -276,18 -277,17 +276,25 @@@ bool DaemonServer::ms_dispatch(Message
  
  void DaemonServer::maybe_ready(int32_t osd_id)
  {
-   Mutex::Locker l(lock);
+   if (pgmap_ready.load()) {
+     // Fast path: we don't need to take lock because pgmap_ready
+     // is already set
+   } else {
+     Mutex::Locker l(lock);
      
-   if (!pgmap_ready && reported_osds.find(osd_id) == reported_osds.end()) {
-     dout(4) << "initial report from osd " << osd_id << dendl;
-     reported_osds.insert(osd_id);
-     std::set<int32_t> up_osds;
+     if (reported_osds.find(osd_id) == reported_osds.end()) {
+       dout(4) << "initial report from osd " << osd_id << dendl;
+       reported_osds.insert(osd_id);
+       std::set<int32_t> up_osds;

++<<<<<<< HEAD
 +    if (reported_osds.find(osd_id) == reported_osds.end()) {
 +      dout(4) << "initial report from osd " << osd_id << dendl;
 +      reported_osds.insert(osd_id);
 +      std::set<int32_t> up_osds;
 +
++=======
++>>>>>>> d209157... mgr: make pgmap_ready atomic to avoid taking lock
        cluster_state.with_osdmap([&](const OSDMap& osdmap) {
            osdmap.get_up_osds(up_osds);
        });
```

**Comment by shinobu-x** [comment]
Cherry-picked dc415f1 to fix:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mgr/ActivePyModules.cc:618:48: error: ‘class DaemonPerfCounters’ has no member named ‘declared_types’
       for (auto typestr : state->perf_counters.declared_types) {
```

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-07_15:13:35-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-11-06_02:23:20-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-08_06:05:18-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-mira/

the failed test is addressed by #18675

**Comment by jcsp** [comment]
Ah, these changes were already included in the bulk backport PR https://github.com/ceph/ceph/pull/18675
