### PR TITLE
jewel: ceph-fuse: failure to remount in startup test does not handle client_die_on_failed_remount properly

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/22378

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick This backport was non-trivial: please give it a closer look?

**Comment by smithfarm** [comment]
retest this please - https://github.com/ceph/ceph/pull/21178 has been merged

**Comment by smithfarm** [comment]
```
ceph_fuse.cc: In member function ‘virtual void* main(int, const char**, const char**)::RemountTest::entry()’:
ceph_fuse.cc:156:61: error: expected primary-expression before ‘bool’
         bool client_try_dentry_invalidate = g_conf->get_val<bool>(
                                                             ^
ceph_fuse.cc:161:71: error: expected primary-expression before ‘bool’
         bool client_die_on_failed_dentry_invalidate = g_conf->get_val<bool>(
                                                                       ^
Makefile:23014: recipe for target 'ceph_fuse.o' failed
```

**Comment by smithfarm** [comment]
trivial merge conflict with #18010 - let's wait until that one is merged

**Comment by smithfarm** [comment]
merge conflict (in PendingReleaseNotes) with #18010 - let the older PR take precedence

**Comment by batrick** [comment]
@theanalyst it shouldn't delay a release but if you're doing more QA anyway then please pull it in.

**Comment by theanalyst** [comment]
@batrick thanks, pulling it in

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-05-23-1939-jewel](https://trello.com/c/bR2qmurS/319-wip-yuri2-testing-2018-05-23-1939-jewel)
